package passwordhash

import (
	"testing"

	"github.com/stretchr/testify/require"
)

// TestVerifyAcceptsBunHash pins verification against a real Bun-generated hash.
// Hash captured in spikes/SPIKE-B-findings.md.
// password: "Password123!"
// hash generated by: Bun.password.hash("Password123!")
const realPassword = "Password123!"
const realHash = "$argon2id$v=19$m=65536,t=2,p=1$KMWnd11HWS0bkxO0MFQYJ46o+Aevnu9XmMDeI+vgz1Y$x8W0A2xI8JCNmLs7AyKWgPEXi5r3D0LOTjKvR9BnF/s"

func TestVerifyAcceptsBunHash(t *testing.T) {
	ok, err := Verify(realPassword, realHash)
	require.NoError(t, err)
	require.True(t, ok, "Go must verify a Bun-generated argon2id hash")
}

func TestVerifyRejectsWrongPassword(t *testing.T) {
	ok, err := Verify("wrongpassword", realHash)
	require.NoError(t, err)
	require.False(t, ok)
}

func TestHashThenVerifyRoundTrip(t *testing.T) {
	h, err := Hash("hunter2")
	require.NoError(t, err)
	require.NotEmpty(t, h)

	ok, err := Verify("hunter2", h)
	require.NoError(t, err)
	require.True(t, ok)

	bad, err := Verify("wrong", h)
	require.NoError(t, err)
	require.False(t, bad)
}

func TestHashProducesArgon2idFormat(t *testing.T) {
	h, err := Hash("test")
	require.NoError(t, err)
	require.Contains(t, h, "$argon2id$v=19$m=65536,t=2,p=1$")
}
