export default {
  login: "admin/auth/login",
  setup: "shared/base/setup",
  status: "admin/auth/status",
  forgotPassword: "/shared/auth/forgot-password",
  verifyOtp: "/shared/auth/verify-otp",
  resetPassword: "/shared/auth/reset-password",
  resendOtp: "/admin/auth/reset-otp",
  sendOtp: "/admin/auth/otp",
  changePassword: "/admin/auth/change-password",
  createRestaurant: "admin/auth/setup",
  fetchDish: "admin/dishes",
  deleteDish: (id: string) => `admin/dishes/${id}`,
  fetchMenuClassification: "admin/menu-classifications",
  getAdminProfile: "/admin/auth/profile",
  updateEmail: "/admin/auth/profile",
  // addDrinkType: "admin/menu-classifications",
  addDish: "admin/dishes/create",
  addItem: "admin/menu-items",
  bulkDishes: "admin/dishes/upload-bulk",
  addDrink: "/admin/drinks/",
  bulkDrinks: "/admin/drinks/upload-bulk",
  fetchDrinks: "/admin/drinks/",
  fetchDrinkTypes: "/admin/drinks/drink-types",
  fetchDrinkUnits: "/admin/drinks/drink-units",
  fetchClassificationCuisine: "admin/menu-classifications/cuisines",
  fetchIngredients: "admin/ingredients",
  addIngredient: "admin/ingredients",
  deleteIngredient: (id: string) => `/admin/ingredients/${id}`,
  fetchReviews: "admin/reviews/",
  fetchAdminStats: "admin/stats/",
  fetchAdminLineChart: "/admin/stats/customers/chart",
  subscriptionList: "admin/subscriptions/system",
  subscribe: "admin/subscriptions",
  cancelSubscription: "admin/subscriptions/cancel",
  addDrinkType: "/admin/drinks/drink-types",
  dishTags: "/admin/dish-tags/",
  fetchDishTagItem: (id: string) => `/admin/dish-tags/dishes/${id}`,
  fetchDrinkTagItem: (id: string) => `/admin/drink-tags/drinks/${id}`,
  removeDishFromTag: (dishId: string, tagId: string) =>
    `/admin/dish-tags/dish/${dishId}/${tagId}`,
  removeDrinkFromTag: (dishId: string, tagId: string) =>
    `/admin/drink-tags/drink/${dishId}/${tagId}`,
  addDishToTag: (dishId: string, tagId: string) =>
    `/admin/dish-tags/dish/${dishId}/${tagId}`,
  addDrinkToTag: (dishId: string, tagId: string) =>
    `/admin/drink-tags/drinks/${dishId}/${tagId}`,
  fetchSpecificDish: (id: string | undefined) => `/admin/dishes/${id}`,
  editDish: (id: string | undefined) => `/admin/dishes/${id}`,
  editMenuItem: (id: string | undefined) => `/admin/menu-items/${id}`,
  fetchSpecificDrink: (id: string | undefined) => `/admin/drinks/${id}`,
  getDishChartByTags: "/admin/stats/dishes-by-tags",
  editDrink: (id: string | undefined) => `/admin/drinks/${id}`,
  deleteDrink: (id: string) => `admin/drinks/${id}`,
  updatePersonalInfo: "/admin/auth/setup",
  menus: "/admin/menu",
  editMenu: (id: string) => `/admin/menu/${id}`,
  deleteMenu: (id: string) => `/admin/menu/${id}`,
  menuSections: (menuId: string) => `/admin/menu-sections/${menuId}`,
  updateMenuSection: (id: string) => `/admin/menu-sections/${id}`,
  deleteMenuSection: (id: string) => `/admin/menu-sections/${id}`,
  menuItems: `/admin/menu-items`,
  bulkUploadMenuItems: "/admin/menu-items/bulk-upload",
  allegens: '/admin/classifications/allergens',
  diets: '/admin/classifications/diets',
  fetchSpecificMenuItem: (id: string | undefined) => `/admin/menu-items/${id}`,
  addOns: (id?: string) => id ? `/admin/addons/${id}` : `/admin/addons`,
  formConfig: (formKey: string) => `admin/form-config/${formKey}`,
  audit: "/admin/audit",
  menusAndSections: "/admin/menu/menus-sections",
  passkeyRegisterBegin: "auth/passkey/register/begin",
  passkeyRegisterFinish: "auth/passkey/register/finish",
  passkeyLoginBegin: "auth/passkey/login/begin",
  passkeyLoginFinish: "auth/passkey/login/finish",
  passkeyStatus: "auth/passkey/status",
  passkeyDelete: (id: string) => `auth/passkey/${id}`,
};
