// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRestaurant = `-- name: CreateRestaurant :one
INSERT INTO restaurants (id, name, description, image, "currencyId", status, created_at)
VALUES (gen_random_uuid(), $1, $2, $3, $4, 'COMPLETED', now())
RETURNING id
`

type CreateRestaurantParams struct {
	Name        *string     `json:"name"`
	Description *string     `json:"description"`
	Image       *string     `json:"image"`
	CurrencyId  pgtype.UUID `json:"currencyId"`
}

func (q *Queries) CreateRestaurant(ctx context.Context, arg CreateRestaurantParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createRestaurant,
		arg.Name,
		arg.Description,
		arg.Image,
		arg.CurrencyId,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getAdminProfile = `-- name: GetAdminProfile :one
SELECT u.id, u.email, u.name, u.role, u.language_id,
       r.id AS restaurant_id, r.name AS restaurant_name, r.address, r.image,
       r.description, r.banner_url, r."currencyId" AS restaurant_currency_id, r.slug
FROM users u
LEFT JOIN restaurants r ON r.id = u.restaurant_id
WHERE u.id = $1
`

type GetAdminProfileRow struct {
	ID                   pgtype.UUID `json:"id"`
	Email                string      `json:"email"`
	Name                 string      `json:"name"`
	Role                 *string     `json:"role"`
	LanguageID           pgtype.UUID `json:"language_id"`
	RestaurantID         pgtype.UUID `json:"restaurant_id"`
	RestaurantName       *string     `json:"restaurant_name"`
	Address              *string     `json:"address"`
	Image                *string     `json:"image"`
	Description          *string     `json:"description"`
	BannerUrl            *string     `json:"banner_url"`
	RestaurantCurrencyID pgtype.UUID `json:"restaurant_currency_id"`
	Slug                 *string     `json:"slug"`
}

func (q *Queries) GetAdminProfile(ctx context.Context, id pgtype.UUID) (GetAdminProfileRow, error) {
	row := q.db.QueryRow(ctx, getAdminProfile, id)
	var i GetAdminProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.LanguageID,
		&i.RestaurantID,
		&i.RestaurantName,
		&i.Address,
		&i.Image,
		&i.Description,
		&i.BannerUrl,
		&i.RestaurantCurrencyID,
		&i.Slug,
	)
	return i, err
}

const getUserWithRestaurantStatus = `-- name: GetUserWithRestaurantStatus :one
SELECT u.id, u.email, u.name, u.role, u.restaurant_id, u.setup_complete,
       r.suspended
FROM users u
LEFT JOIN restaurants r ON r.id = u.restaurant_id
WHERE u.id = $1
`

type GetUserWithRestaurantStatusRow struct {
	ID            pgtype.UUID `json:"id"`
	Email         string      `json:"email"`
	Name          string      `json:"name"`
	Role          *string     `json:"role"`
	RestaurantID  pgtype.UUID `json:"restaurant_id"`
	SetupComplete *bool       `json:"setup_complete"`
	Suspended     *bool       `json:"suspended"`
}

func (q *Queries) GetUserWithRestaurantStatus(ctx context.Context, id pgtype.UUID) (GetUserWithRestaurantStatusRow, error) {
	row := q.db.QueryRow(ctx, getUserWithRestaurantStatus, id)
	var i GetUserWithRestaurantStatusRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.RestaurantID,
		&i.SetupComplete,
		&i.Suspended,
	)
	return i, err
}

const linkUserToRestaurant = `-- name: LinkUserToRestaurant :exec
UPDATE users SET restaurant_id = $1, language_id = $2, setup_complete = true, updated_at = now()
WHERE id = $3
`

type LinkUserToRestaurantParams struct {
	RestaurantID pgtype.UUID `json:"restaurant_id"`
	LanguageID   pgtype.UUID `json:"language_id"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) LinkUserToRestaurant(ctx context.Context, arg LinkUserToRestaurantParams) error {
	_, err := q.db.Exec(ctx, linkUserToRestaurant, arg.RestaurantID, arg.LanguageID, arg.ID)
	return err
}

const updateRestaurantForSetup = `-- name: UpdateRestaurantForSetup :exec
UPDATE restaurants SET name = $1, description = $2, image = COALESCE($3, image),
                       "currencyId" = $4, status = 'COMPLETED'
WHERE id = $5
`

type UpdateRestaurantForSetupParams struct {
	Name        *string     `json:"name"`
	Description *string     `json:"description"`
	Image       *string     `json:"image"`
	CurrencyId  pgtype.UUID `json:"currencyId"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateRestaurantForSetup(ctx context.Context, arg UpdateRestaurantForSetupParams) error {
	_, err := q.db.Exec(ctx, updateRestaurantForSetup,
		arg.Name,
		arg.Description,
		arg.Image,
		arg.CurrencyId,
		arg.ID,
	)
	return err
}

const updateRestaurantInfo = `-- name: UpdateRestaurantInfo :exec
UPDATE restaurants SET
    name        = COALESCE($1, name),
    description = COALESCE($2, description),
    image       = COALESCE($3, image),
    address     = COALESCE($4, address),
    banner_url  = COALESCE($5, banner_url),
    "currencyId"= COALESCE($6, "currencyId")
WHERE id = $7
`

type UpdateRestaurantInfoParams struct {
	Name        *string     `json:"name"`
	Description *string     `json:"description"`
	Image       *string     `json:"image"`
	Address     *string     `json:"address"`
	BannerUrl   *string     `json:"banner_url"`
	CurrencyId  pgtype.UUID `json:"currencyId"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateRestaurantInfo(ctx context.Context, arg UpdateRestaurantInfoParams) error {
	_, err := q.db.Exec(ctx, updateRestaurantInfo,
		arg.Name,
		arg.Description,
		arg.Image,
		arg.Address,
		arg.BannerUrl,
		arg.CurrencyId,
		arg.ID,
	)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE users SET email = $1, updated_at = now() WHERE id = $2
`

type UpdateUserEmailParams struct {
	Email string      `json:"email"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.Exec(ctx, updateUserEmail, arg.Email, arg.ID)
	return err
}

const updateUserLanguage = `-- name: UpdateUserLanguage :exec
UPDATE users SET language_id = $1, updated_at = now() WHERE id = $2
`

type UpdateUserLanguageParams struct {
	LanguageID pgtype.UUID `json:"language_id"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserLanguage(ctx context.Context, arg UpdateUserLanguageParams) error {
	_, err := q.db.Exec(ctx, updateUserLanguage, arg.LanguageID, arg.ID)
	return err
}
