// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_menu.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMenuItemsForAdmin = `-- name: CountMenuItemsForAdmin :one
SELECT COUNT(*) FROM menu_items
WHERE restaurant_id = $1
  AND (NOT $2 OR section_id = $3)
  AND (NOT $4 OR lower(name) LIKE $5)
`

type CountMenuItemsForAdminParams struct {
	RestaurantID pgtype.UUID `json:"restaurant_id"`
	Column2      interface{} `json:"column_2"`
	SectionID    pgtype.UUID `json:"section_id"`
	Column4      interface{} `json:"column_4"`
	Name         string      `json:"name"`
}

func (q *Queries) CountMenuItemsForAdmin(ctx context.Context, arg CountMenuItemsForAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMenuItemsForAdmin,
		arg.RestaurantID,
		arg.Column2,
		arg.SectionID,
		arg.Column4,
		arg.Name,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMenu = `-- name: CreateMenu :one
INSERT INTO menu (id, restaurant_id, name, translation_status, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, 'pending', now(), now())
RETURNING id, name, description, active, start_time, end_time, created_at, updated_at
`

type CreateMenuParams struct {
	RestaurantID pgtype.UUID `json:"restaurant_id"`
	Name         string      `json:"name"`
}

type CreateMenuRow struct {
	ID          pgtype.UUID      `json:"id"`
	Name        string           `json:"name"`
	Description *string          `json:"description"`
	Active      *bool            `json:"active"`
	StartTime   *string          `json:"start_time"`
	EndTime     *string          `json:"end_time"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateMenu(ctx context.Context, arg CreateMenuParams) (CreateMenuRow, error) {
	row := q.db.QueryRow(ctx, createMenu, arg.RestaurantID, arg.Name)
	var i CreateMenuRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMenuItem = `-- name: CreateMenuItem :one
INSERT INTO menu_items (id, section_id, restaurant_id, name, description, images, price, type,
    discount_type, discount_value, discount_start_at, discount_end_at, discount_label,
    ingredients, is_available, spice_level, cook_time, is_alcoholic, has_variants,
    is_chefs_recommended, is_popular, is_new, is_limited_time, translation_status, created_at)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18,
    $19, $20, $21, $22, 'pending', now())
RETURNING id
`

type CreateMenuItemParams struct {
	SectionID          pgtype.UUID      `json:"section_id"`
	RestaurantID       pgtype.UUID      `json:"restaurant_id"`
	Name               string           `json:"name"`
	Description        *string          `json:"description"`
	Images             []string         `json:"images"`
	Price              pgtype.Numeric   `json:"price"`
	Type               string           `json:"type"`
	DiscountType       *string          `json:"discount_type"`
	DiscountValue      pgtype.Numeric   `json:"discount_value"`
	DiscountStartAt    pgtype.Timestamp `json:"discount_start_at"`
	DiscountEndAt      pgtype.Timestamp `json:"discount_end_at"`
	DiscountLabel      *string          `json:"discount_label"`
	Ingredients        []string         `json:"ingredients"`
	IsAvailable        *bool            `json:"is_available"`
	SpiceLevel         *SpiceLevel      `json:"spice_level"`
	CookTime           *int32           `json:"cook_time"`
	IsAlcoholic        *bool            `json:"is_alcoholic"`
	HasVariants        *bool            `json:"has_variants"`
	IsChefsRecommended *bool            `json:"is_chefs_recommended"`
	IsPopular          *bool            `json:"is_popular"`
	IsNew              *bool            `json:"is_new"`
	IsLimitedTime      *bool            `json:"is_limited_time"`
}

func (q *Queries) CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createMenuItem,
		arg.SectionID,
		arg.RestaurantID,
		arg.Name,
		arg.Description,
		arg.Images,
		arg.Price,
		arg.Type,
		arg.DiscountType,
		arg.DiscountValue,
		arg.DiscountStartAt,
		arg.DiscountEndAt,
		arg.DiscountLabel,
		arg.Ingredients,
		arg.IsAvailable,
		arg.SpiceLevel,
		arg.CookTime,
		arg.IsAlcoholic,
		arg.HasVariants,
		arg.IsChefsRecommended,
		arg.IsPopular,
		arg.IsNew,
		arg.IsLimitedTime,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createMenuSection = `-- name: CreateMenuSection :one
INSERT INTO menu_sections (id, menu_id, name, description, created_at)
VALUES (gen_random_uuid(), $1, lower($2), $3, now())
RETURNING id
`

type CreateMenuSectionParams struct {
	MenuID      pgtype.UUID `json:"menu_id"`
	Lower       string      `json:"lower"`
	Description *string     `json:"description"`
}

func (q *Queries) CreateMenuSection(ctx context.Context, arg CreateMenuSectionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createMenuSection, arg.MenuID, arg.Lower, arg.Description)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteMenu = `-- name: DeleteMenu :exec
DELETE FROM menu WHERE id = $1 AND restaurant_id = $2
`

type DeleteMenuParams struct {
	ID           pgtype.UUID `json:"id"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
}

func (q *Queries) DeleteMenu(ctx context.Context, arg DeleteMenuParams) error {
	_, err := q.db.Exec(ctx, deleteMenu, arg.ID, arg.RestaurantID)
	return err
}

const deleteMenuItem = `-- name: DeleteMenuItem :exec
DELETE FROM menu_items WHERE id = $1 AND restaurant_id = $2
`

type DeleteMenuItemParams struct {
	ID           pgtype.UUID `json:"id"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
}

func (q *Queries) DeleteMenuItem(ctx context.Context, arg DeleteMenuItemParams) error {
	_, err := q.db.Exec(ctx, deleteMenuItem, arg.ID, arg.RestaurantID)
	return err
}

const deleteMenuItemAddons = `-- name: DeleteMenuItemAddons :exec
DELETE FROM menu_item_addons WHERE item_id = $1
`

func (q *Queries) DeleteMenuItemAddons(ctx context.Context, itemID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMenuItemAddons, itemID)
	return err
}

const deleteMenuItemAllergens = `-- name: DeleteMenuItemAllergens :exec
DELETE FROM menu_item_allergens WHERE menu_item_id = $1
`

func (q *Queries) DeleteMenuItemAllergens(ctx context.Context, menuItemID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMenuItemAllergens, menuItemID)
	return err
}

const deleteMenuItemTags = `-- name: DeleteMenuItemTags :exec
DELETE FROM menu_item_tags WHERE menu_item_id = $1
`

func (q *Queries) DeleteMenuItemTags(ctx context.Context, menuItemID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMenuItemTags, menuItemID)
	return err
}

const deleteMenuItemVariants = `-- name: DeleteMenuItemVariants :exec
DELETE FROM menu_item_variants WHERE item_id = $1
`

func (q *Queries) DeleteMenuItemVariants(ctx context.Context, itemID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMenuItemVariants, itemID)
	return err
}

const deleteMenuSection = `-- name: DeleteMenuSection :exec
DELETE FROM menu_sections WHERE menu_sections.id = $1
  AND menu_sections.menu_id IN (SELECT m.id FROM menu m WHERE m.restaurant_id = $2)
`

type DeleteMenuSectionParams struct {
	ID           pgtype.UUID `json:"id"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
}

func (q *Queries) DeleteMenuSection(ctx context.Context, arg DeleteMenuSectionParams) error {
	_, err := q.db.Exec(ctx, deleteMenuSection, arg.ID, arg.RestaurantID)
	return err
}

const getAdminMenuItemByID = `-- name: GetAdminMenuItemByID :one
SELECT id, section_id, name, description, translations, ingredients, images, price, type,
       discount_type, discount_value, discount_start_at, discount_end_at, discount_label,
       is_available, spice_level, cook_time, is_alcoholic, has_variants,
       is_chefs_recommended, is_popular, is_new, is_limited_time, created_at
FROM menu_items WHERE id = $1 AND restaurant_id = $2
`

type GetAdminMenuItemByIDParams struct {
	ID           pgtype.UUID `json:"id"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
}

type GetAdminMenuItemByIDRow struct {
	ID                 pgtype.UUID      `json:"id"`
	SectionID          pgtype.UUID      `json:"section_id"`
	Name               string           `json:"name"`
	Description        *string          `json:"description"`
	Translations       []byte           `json:"translations"`
	Ingredients        []string         `json:"ingredients"`
	Images             []string         `json:"images"`
	Price              pgtype.Numeric   `json:"price"`
	Type               string           `json:"type"`
	DiscountType       *string          `json:"discount_type"`
	DiscountValue      pgtype.Numeric   `json:"discount_value"`
	DiscountStartAt    pgtype.Timestamp `json:"discount_start_at"`
	DiscountEndAt      pgtype.Timestamp `json:"discount_end_at"`
	DiscountLabel      *string          `json:"discount_label"`
	IsAvailable        *bool            `json:"is_available"`
	SpiceLevel         *SpiceLevel      `json:"spice_level"`
	CookTime           *int32           `json:"cook_time"`
	IsAlcoholic        *bool            `json:"is_alcoholic"`
	HasVariants        *bool            `json:"has_variants"`
	IsChefsRecommended *bool            `json:"is_chefs_recommended"`
	IsPopular          *bool            `json:"is_popular"`
	IsNew              *bool            `json:"is_new"`
	IsLimitedTime      *bool            `json:"is_limited_time"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetAdminMenuItemByID(ctx context.Context, arg GetAdminMenuItemByIDParams) (GetAdminMenuItemByIDRow, error) {
	row := q.db.QueryRow(ctx, getAdminMenuItemByID, arg.ID, arg.RestaurantID)
	var i GetAdminMenuItemByIDRow
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Name,
		&i.Description,
		&i.Translations,
		&i.Ingredients,
		&i.Images,
		&i.Price,
		&i.Type,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountStartAt,
		&i.DiscountEndAt,
		&i.DiscountLabel,
		&i.IsAvailable,
		&i.SpiceLevel,
		&i.CookTime,
		&i.IsAlcoholic,
		&i.HasVariants,
		&i.IsChefsRecommended,
		&i.IsPopular,
		&i.IsNew,
		&i.IsLimitedTime,
		&i.CreatedAt,
	)
	return i, err
}

const getMenuByIDForAdmin = `-- name: GetMenuByIDForAdmin :one
SELECT id, name, description, translations, active, start_time, end_time, translation_status, created_at, updated_at
FROM menu WHERE id = $1 AND restaurant_id = $2
`

type GetMenuByIDForAdminParams struct {
	ID           pgtype.UUID `json:"id"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
}

type GetMenuByIDForAdminRow struct {
	ID                pgtype.UUID      `json:"id"`
	Name              string           `json:"name"`
	Description       *string          `json:"description"`
	Translations      []byte           `json:"translations"`
	Active            *bool            `json:"active"`
	StartTime         *string          `json:"start_time"`
	EndTime           *string          `json:"end_time"`
	TranslationStatus *string          `json:"translation_status"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetMenuByIDForAdmin(ctx context.Context, arg GetMenuByIDForAdminParams) (GetMenuByIDForAdminRow, error) {
	row := q.db.QueryRow(ctx, getMenuByIDForAdmin, arg.ID, arg.RestaurantID)
	var i GetMenuByIDForAdminRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Translations,
		&i.Active,
		&i.StartTime,
		&i.EndTime,
		&i.TranslationStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMenuSectionByID = `-- name: GetMenuSectionByID :one
SELECT ms.id, ms.menu_id, ms.name, ms.description
FROM menu_sections ms
JOIN menu m ON ms.menu_id = m.id
WHERE ms.id = $1 AND m.restaurant_id = $2
`

type GetMenuSectionByIDParams struct {
	ID           pgtype.UUID `json:"id"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
}

type GetMenuSectionByIDRow struct {
	ID          pgtype.UUID `json:"id"`
	MenuID      pgtype.UUID `json:"menu_id"`
	Name        string      `json:"name"`
	Description *string     `json:"description"`
}

func (q *Queries) GetMenuSectionByID(ctx context.Context, arg GetMenuSectionByIDParams) (GetMenuSectionByIDRow, error) {
	row := q.db.QueryRow(ctx, getMenuSectionByID, arg.ID, arg.RestaurantID)
	var i GetMenuSectionByIDRow
	err := row.Scan(
		&i.ID,
		&i.MenuID,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const insertMenuItemAddon = `-- name: InsertMenuItemAddon :exec
INSERT INTO menu_item_addons (item_id, addon_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type InsertMenuItemAddonParams struct {
	ItemID  pgtype.UUID `json:"item_id"`
	AddonID pgtype.UUID `json:"addon_id"`
}

func (q *Queries) InsertMenuItemAddon(ctx context.Context, arg InsertMenuItemAddonParams) error {
	_, err := q.db.Exec(ctx, insertMenuItemAddon, arg.ItemID, arg.AddonID)
	return err
}

const insertMenuItemAllergen = `-- name: InsertMenuItemAllergen :exec
INSERT INTO menu_item_allergens (id, menu_item_id, allergen_id)
VALUES (gen_random_uuid(), $1, $2)
ON CONFLICT DO NOTHING
`

type InsertMenuItemAllergenParams struct {
	MenuItemID pgtype.UUID `json:"menu_item_id"`
	AllergenID pgtype.UUID `json:"allergen_id"`
}

func (q *Queries) InsertMenuItemAllergen(ctx context.Context, arg InsertMenuItemAllergenParams) error {
	_, err := q.db.Exec(ctx, insertMenuItemAllergen, arg.MenuItemID, arg.AllergenID)
	return err
}

const insertMenuItemTag = `-- name: InsertMenuItemTag :exec
INSERT INTO menu_item_tags (id, menu_item_id, tag_id)
VALUES (gen_random_uuid(), $1, $2)
ON CONFLICT DO NOTHING
`

type InsertMenuItemTagParams struct {
	MenuItemID pgtype.UUID `json:"menu_item_id"`
	TagID      pgtype.UUID `json:"tag_id"`
}

func (q *Queries) InsertMenuItemTag(ctx context.Context, arg InsertMenuItemTagParams) error {
	_, err := q.db.Exec(ctx, insertMenuItemTag, arg.MenuItemID, arg.TagID)
	return err
}

const insertMenuItemVariant = `-- name: InsertMenuItemVariant :one
INSERT INTO menu_item_variants (id, item_id, name, price, is_available, image, created_at)
VALUES (gen_random_uuid(), $1, $2, $3, true, $4, now())
RETURNING id
`

type InsertMenuItemVariantParams struct {
	ItemID pgtype.UUID    `json:"item_id"`
	Name   string         `json:"name"`
	Price  pgtype.Numeric `json:"price"`
	Image  *string        `json:"image"`
}

func (q *Queries) InsertMenuItemVariant(ctx context.Context, arg InsertMenuItemVariantParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertMenuItemVariant,
		arg.ItemID,
		arg.Name,
		arg.Price,
		arg.Image,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listAdminSectionsByMenu = `-- name: ListAdminSectionsByMenu :many
SELECT id, name, sort_order, menu_id, description, translations
FROM menu_sections WHERE menu_id = $1 ORDER BY sort_order DESC
`

type ListAdminSectionsByMenuRow struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	SortOrder    *int32      `json:"sort_order"`
	MenuID       pgtype.UUID `json:"menu_id"`
	Description  *string     `json:"description"`
	Translations []byte      `json:"translations"`
}

func (q *Queries) ListAdminSectionsByMenu(ctx context.Context, menuID pgtype.UUID) ([]ListAdminSectionsByMenuRow, error) {
	rows, err := q.db.Query(ctx, listAdminSectionsByMenu, menuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminSectionsByMenuRow
	for rows.Next() {
		var i ListAdminSectionsByMenuRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SortOrder,
			&i.MenuID,
			&i.Description,
			&i.Translations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuItemsByMenuForAdmin = `-- name: ListMenuItemsByMenuForAdmin :many
SELECT id, name, description, translations, images, price, type, section_id, is_available,
       is_chefs_recommended, is_popular, is_new, is_limited_time, created_at
FROM menu_items WHERE section_id IN (
    SELECT id FROM menu_sections WHERE menu_id = $1
)
`

type ListMenuItemsByMenuForAdminRow struct {
	ID                 pgtype.UUID      `json:"id"`
	Name               string           `json:"name"`
	Description        *string          `json:"description"`
	Translations       []byte           `json:"translations"`
	Images             []string         `json:"images"`
	Price              pgtype.Numeric   `json:"price"`
	Type               string           `json:"type"`
	SectionID          pgtype.UUID      `json:"section_id"`
	IsAvailable        *bool            `json:"is_available"`
	IsChefsRecommended *bool            `json:"is_chefs_recommended"`
	IsPopular          *bool            `json:"is_popular"`
	IsNew              *bool            `json:"is_new"`
	IsLimitedTime      *bool            `json:"is_limited_time"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) ListMenuItemsByMenuForAdmin(ctx context.Context, menuID pgtype.UUID) ([]ListMenuItemsByMenuForAdminRow, error) {
	rows, err := q.db.Query(ctx, listMenuItemsByMenuForAdmin, menuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMenuItemsByMenuForAdminRow
	for rows.Next() {
		var i ListMenuItemsByMenuForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Translations,
			&i.Images,
			&i.Price,
			&i.Type,
			&i.SectionID,
			&i.IsAvailable,
			&i.IsChefsRecommended,
			&i.IsPopular,
			&i.IsNew,
			&i.IsLimitedTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuItemsForAdmin = `-- name: ListMenuItemsForAdmin :many
SELECT id, section_id, name, description, translations, images, price, type,
       discount_type, discount_value, discount_label, is_available,
       is_chefs_recommended, is_popular, is_new, is_limited_time, has_variants,
       cook_time, spice_level, is_alcoholic, created_at
FROM menu_items
WHERE restaurant_id = $1
  AND (NOT $2 OR section_id = $3)
  AND (NOT $4 OR lower(name) LIKE $5)
ORDER BY created_at DESC
LIMIT $6 OFFSET $7
`

type ListMenuItemsForAdminParams struct {
	RestaurantID pgtype.UUID `json:"restaurant_id"`
	Column2      interface{} `json:"column_2"`
	SectionID    pgtype.UUID `json:"section_id"`
	Column4      interface{} `json:"column_4"`
	Name         string      `json:"name"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
}

type ListMenuItemsForAdminRow struct {
	ID                 pgtype.UUID      `json:"id"`
	SectionID          pgtype.UUID      `json:"section_id"`
	Name               string           `json:"name"`
	Description        *string          `json:"description"`
	Translations       []byte           `json:"translations"`
	Images             []string         `json:"images"`
	Price              pgtype.Numeric   `json:"price"`
	Type               string           `json:"type"`
	DiscountType       *string          `json:"discount_type"`
	DiscountValue      pgtype.Numeric   `json:"discount_value"`
	DiscountLabel      *string          `json:"discount_label"`
	IsAvailable        *bool            `json:"is_available"`
	IsChefsRecommended *bool            `json:"is_chefs_recommended"`
	IsPopular          *bool            `json:"is_popular"`
	IsNew              *bool            `json:"is_new"`
	IsLimitedTime      *bool            `json:"is_limited_time"`
	HasVariants        *bool            `json:"has_variants"`
	CookTime           *int32           `json:"cook_time"`
	SpiceLevel         *SpiceLevel      `json:"spice_level"`
	IsAlcoholic        *bool            `json:"is_alcoholic"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) ListMenuItemsForAdmin(ctx context.Context, arg ListMenuItemsForAdminParams) ([]ListMenuItemsForAdminRow, error) {
	rows, err := q.db.Query(ctx, listMenuItemsForAdmin,
		arg.RestaurantID,
		arg.Column2,
		arg.SectionID,
		arg.Column4,
		arg.Name,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMenuItemsForAdminRow
	for rows.Next() {
		var i ListMenuItemsForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.SectionID,
			&i.Name,
			&i.Description,
			&i.Translations,
			&i.Images,
			&i.Price,
			&i.Type,
			&i.DiscountType,
			&i.DiscountValue,
			&i.DiscountLabel,
			&i.IsAvailable,
			&i.IsChefsRecommended,
			&i.IsPopular,
			&i.IsNew,
			&i.IsLimitedTime,
			&i.HasVariants,
			&i.CookTime,
			&i.SpiceLevel,
			&i.IsAlcoholic,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenusWithSections = `-- name: ListMenusWithSections :many
SELECT m.id AS menu_id, m.name AS menu_name, m.translations AS menu_translations,
       ms.id AS section_id, ms.name AS section_name, ms.sort_order, ms.translations AS section_translations
FROM menu m
LEFT JOIN menu_sections ms ON ms.menu_id = m.id
WHERE m.restaurant_id = $1
ORDER BY m.created_at, ms.sort_order
`

type ListMenusWithSectionsRow struct {
	MenuID              pgtype.UUID `json:"menu_id"`
	MenuName            string      `json:"menu_name"`
	MenuTranslations    []byte      `json:"menu_translations"`
	SectionID           pgtype.UUID `json:"section_id"`
	SectionName         *string     `json:"section_name"`
	SortOrder           *int32      `json:"sort_order"`
	SectionTranslations []byte      `json:"section_translations"`
}

func (q *Queries) ListMenusWithSections(ctx context.Context, restaurantID pgtype.UUID) ([]ListMenusWithSectionsRow, error) {
	rows, err := q.db.Query(ctx, listMenusWithSections, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMenusWithSectionsRow
	for rows.Next() {
		var i ListMenusWithSectionsRow
		if err := rows.Scan(
			&i.MenuID,
			&i.MenuName,
			&i.MenuTranslations,
			&i.SectionID,
			&i.SectionName,
			&i.SortOrder,
			&i.SectionTranslations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const menuBelongsToRestaurant = `-- name: MenuBelongsToRestaurant :one
SELECT id FROM menu WHERE id = $1 AND restaurant_id = $2
`

type MenuBelongsToRestaurantParams struct {
	ID           pgtype.UUID `json:"id"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
}

func (q *Queries) MenuBelongsToRestaurant(ctx context.Context, arg MenuBelongsToRestaurantParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, menuBelongsToRestaurant, arg.ID, arg.RestaurantID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const moveMenuItemsToSection = `-- name: MoveMenuItemsToSection :exec
UPDATE menu_items SET section_id = $1 WHERE section_id = $2
`

type MoveMenuItemsToSectionParams struct {
	SectionID   pgtype.UUID `json:"section_id"`
	SectionID_2 pgtype.UUID `json:"section_id_2"`
}

func (q *Queries) MoveMenuItemsToSection(ctx context.Context, arg MoveMenuItemsToSectionParams) error {
	_, err := q.db.Exec(ctx, moveMenuItemsToSection, arg.SectionID, arg.SectionID_2)
	return err
}

const sectionBelongsToRestaurant = `-- name: SectionBelongsToRestaurant :one
SELECT ms.id FROM menu_sections ms
JOIN menu m ON ms.menu_id = m.id
WHERE ms.id = $1 AND m.restaurant_id = $2
`

type SectionBelongsToRestaurantParams struct {
	ID           pgtype.UUID `json:"id"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
}

func (q *Queries) SectionBelongsToRestaurant(ctx context.Context, arg SectionBelongsToRestaurantParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, sectionBelongsToRestaurant, arg.ID, arg.RestaurantID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updateMenu = `-- name: UpdateMenu :exec
UPDATE menu SET name = COALESCE(NULLIF($1, ''), name), description = COALESCE($2, description),
                active = COALESCE($3, active), start_time = COALESCE($4, start_time),
                end_time = COALESCE($5, end_time), translation_status = 'pending', updated_at = now()
WHERE id = $6 AND restaurant_id = $7
`

type UpdateMenuParams struct {
	Column1      interface{} `json:"column_1"`
	Description  *string     `json:"description"`
	Active       *bool       `json:"active"`
	StartTime    *string     `json:"start_time"`
	EndTime      *string     `json:"end_time"`
	ID           pgtype.UUID `json:"id"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
}

func (q *Queries) UpdateMenu(ctx context.Context, arg UpdateMenuParams) error {
	_, err := q.db.Exec(ctx, updateMenu,
		arg.Column1,
		arg.Description,
		arg.Active,
		arg.StartTime,
		arg.EndTime,
		arg.ID,
		arg.RestaurantID,
	)
	return err
}

const updateMenuItem = `-- name: UpdateMenuItem :exec
UPDATE menu_items SET
    name        = COALESCE(NULLIF($1, ''), name),
    description = COALESCE($2, description),
    images      = COALESCE($3, images),
    price       = COALESCE($4, price),
    discount_type       = COALESCE($5, discount_type),
    discount_value      = COALESCE($6, discount_value),
    discount_start_at   = COALESCE($7, discount_start_at),
    discount_end_at     = COALESCE($8, discount_end_at),
    discount_label      = COALESCE($9, discount_label),
    ingredients         = COALESCE($10, ingredients),
    is_available        = COALESCE($11, is_available),
    spice_level         = COALESCE($12, spice_level),
    cook_time           = COALESCE($13, cook_time),
    is_alcoholic        = COALESCE($14, is_alcoholic),
    has_variants        = COALESCE($15, has_variants),
    is_chefs_recommended= COALESCE($16, is_chefs_recommended),
    is_popular          = COALESCE($17, is_popular),
    is_new              = COALESCE($18, is_new),
    is_limited_time     = COALESCE($19, is_limited_time),
    translation_status  = 'pending'
WHERE id = $20 AND restaurant_id = $21
`

type UpdateMenuItemParams struct {
	Column1            interface{}      `json:"column_1"`
	Description        *string          `json:"description"`
	Images             []string         `json:"images"`
	Price              pgtype.Numeric   `json:"price"`
	DiscountType       *string          `json:"discount_type"`
	DiscountValue      pgtype.Numeric   `json:"discount_value"`
	DiscountStartAt    pgtype.Timestamp `json:"discount_start_at"`
	DiscountEndAt      pgtype.Timestamp `json:"discount_end_at"`
	DiscountLabel      *string          `json:"discount_label"`
	Ingredients        []string         `json:"ingredients"`
	IsAvailable        *bool            `json:"is_available"`
	SpiceLevel         *SpiceLevel      `json:"spice_level"`
	CookTime           *int32           `json:"cook_time"`
	IsAlcoholic        *bool            `json:"is_alcoholic"`
	HasVariants        *bool            `json:"has_variants"`
	IsChefsRecommended *bool            `json:"is_chefs_recommended"`
	IsPopular          *bool            `json:"is_popular"`
	IsNew              *bool            `json:"is_new"`
	IsLimitedTime      *bool            `json:"is_limited_time"`
	ID                 pgtype.UUID      `json:"id"`
	RestaurantID       pgtype.UUID      `json:"restaurant_id"`
}

func (q *Queries) UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) error {
	_, err := q.db.Exec(ctx, updateMenuItem,
		arg.Column1,
		arg.Description,
		arg.Images,
		arg.Price,
		arg.DiscountType,
		arg.DiscountValue,
		arg.DiscountStartAt,
		arg.DiscountEndAt,
		arg.DiscountLabel,
		arg.Ingredients,
		arg.IsAvailable,
		arg.SpiceLevel,
		arg.CookTime,
		arg.IsAlcoholic,
		arg.HasVariants,
		arg.IsChefsRecommended,
		arg.IsPopular,
		arg.IsNew,
		arg.IsLimitedTime,
		arg.ID,
		arg.RestaurantID,
	)
	return err
}

const updateMenuSection = `-- name: UpdateMenuSection :exec
UPDATE menu_sections SET name = COALESCE(NULLIF(lower($1), ''), name),
                         description = COALESCE($2, description),
                         translation_status = 'pending'
WHERE menu_sections.id = $3
  AND menu_sections.menu_id IN (SELECT m.id FROM menu m WHERE m.restaurant_id = $4)
`

type UpdateMenuSectionParams struct {
	Lower        string      `json:"lower"`
	Description  *string     `json:"description"`
	ID           pgtype.UUID `json:"id"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
}

func (q *Queries) UpdateMenuSection(ctx context.Context, arg UpdateMenuSectionParams) error {
	_, err := q.db.Exec(ctx, updateMenuSection,
		arg.Lower,
		arg.Description,
		arg.ID,
		arg.RestaurantID,
	)
	return err
}
