// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_data.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkDietTagExists = `-- name: CheckDietTagExists :one
SELECT id FROM tags
WHERE lower(name) = lower($1) AND type = 'diet' AND restaurant_id = $2
LIMIT 1
`

type CheckDietTagExistsParams struct {
	Lower        string      `json:"lower"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
}

func (q *Queries) CheckDietTagExists(ctx context.Context, arg CheckDietTagExistsParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, checkDietTagExists, arg.Lower, arg.RestaurantID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const checkDietTagKeyExists = `-- name: CheckDietTagKeyExists :one
SELECT id FROM tags
WHERE key = $1 AND type = 'diet' AND restaurant_id = $2 AND id != $3
LIMIT 1
`

type CheckDietTagKeyExistsParams struct {
	Key          string      `json:"key"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) CheckDietTagKeyExists(ctx context.Context, arg CheckDietTagKeyExistsParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, checkDietTagKeyExists, arg.Key, arg.RestaurantID, arg.ID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const countAIUsage = `-- name: CountAIUsage :one
SELECT COUNT(*) FROM ai_usage_logs WHERE restaurant_id = $1
`

func (q *Queries) CountAIUsage(ctx context.Context, restaurantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAIUsage, restaurantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT COUNT(*) FROM audit_logs WHERE restaurant_id = $1
`

func (q *Queries) CountAuditLogs(ctx context.Context, restaurantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs, restaurantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMenuItems = `-- name: CountMenuItems :one
SELECT COUNT(*) FROM menu_items WHERE restaurant_id = $1
`

func (q *Queries) CountMenuItems(ctx context.Context, restaurantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMenuItems, restaurantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReviews = `-- name: CountReviews :one
SELECT COUNT(*) FROM reviews WHERE restaurant_id = $1
`

func (q *Queries) CountReviews(ctx context.Context, restaurantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countReviews, restaurantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserSessions = `-- name: CountUserSessions :one
SELECT COUNT(*) FROM user_sessions WHERE restaurant_id = $1
`

func (q *Queries) CountUserSessions(ctx context.Context, restaurantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserSessions, restaurantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAddon = `-- name: CreateAddon :one
INSERT INTO addons (id, restaurant_id, name, price, translation_status, created_at)
VALUES (gen_random_uuid(), $1, lower($2), $3, 'pending', now())
RETURNING id
`

type CreateAddonParams struct {
	RestaurantID pgtype.UUID    `json:"restaurant_id"`
	Lower        string         `json:"lower"`
	Price        pgtype.Numeric `json:"price"`
}

func (q *Queries) CreateAddon(ctx context.Context, arg CreateAddonParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createAddon, arg.RestaurantID, arg.Lower, arg.Price)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createDietTag = `-- name: CreateDietTag :one
INSERT INTO tags (id, name, key, type, restaurant_id, translation_status, created_at)
VALUES (gen_random_uuid(), lower($1), $2, 'diet', $3, 'pending', now())
RETURNING id
`

type CreateDietTagParams struct {
	Lower        string      `json:"lower"`
	Key          string      `json:"key"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
}

func (q *Queries) CreateDietTag(ctx context.Context, arg CreateDietTagParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createDietTag, arg.Lower, arg.Key, arg.RestaurantID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteAddon = `-- name: DeleteAddon :exec
DELETE FROM addons WHERE id = $1 AND restaurant_id = $2
`

type DeleteAddonParams struct {
	ID           pgtype.UUID `json:"id"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
}

func (q *Queries) DeleteAddon(ctx context.Context, arg DeleteAddonParams) error {
	_, err := q.db.Exec(ctx, deleteAddon, arg.ID, arg.RestaurantID)
	return err
}

const deleteDietTag = `-- name: DeleteDietTag :exec
DELETE FROM tags WHERE id = $1 AND type = 'diet' AND restaurant_id = $2 AND is_system = false
`

type DeleteDietTagParams struct {
	ID           pgtype.UUID `json:"id"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
}

func (q *Queries) DeleteDietTag(ctx context.Context, arg DeleteDietTagParams) error {
	_, err := q.db.Exec(ctx, deleteDietTag, arg.ID, arg.RestaurantID)
	return err
}

const dishesByTagCount = `-- name: DishesByTagCount :many
SELECT t.name AS tag_name, COUNT(mit.menu_item_id)::bigint AS count
FROM menu_item_tags mit
JOIN tags t ON mit.tag_id = t.id
WHERE (t.restaurant_id = $1 OR t.is_system = true) AND t.type = 'diet'
GROUP BY t.name
ORDER BY COUNT(mit.menu_item_id) DESC
`

type DishesByTagCountRow struct {
	TagName string `json:"tag_name"`
	Count   int64  `json:"count"`
}

func (q *Queries) DishesByTagCount(ctx context.Context, restaurantID pgtype.UUID) ([]DishesByTagCountRow, error) {
	rows, err := q.db.Query(ctx, dishesByTagCount, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DishesByTagCountRow
	for rows.Next() {
		var i DishesByTagCountRow
		if err := rows.Scan(&i.TagName, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAddonByID = `-- name: GetAddonByID :one
SELECT id, name, price, translations FROM addons WHERE id = $1 AND restaurant_id = $2
`

type GetAddonByIDParams struct {
	ID           pgtype.UUID `json:"id"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
}

type GetAddonByIDRow struct {
	ID           pgtype.UUID    `json:"id"`
	Name         string         `json:"name"`
	Price        pgtype.Numeric `json:"price"`
	Translations []byte         `json:"translations"`
}

func (q *Queries) GetAddonByID(ctx context.Context, arg GetAddonByIDParams) (GetAddonByIDRow, error) {
	row := q.db.QueryRow(ctx, getAddonByID, arg.ID, arg.RestaurantID)
	var i GetAddonByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Price,
		&i.Translations,
	)
	return i, err
}

const getDietTagByID = `-- name: GetDietTagByID :one
SELECT id, name, key FROM tags WHERE id = $1 AND type = 'diet' AND restaurant_id = $2
`

type GetDietTagByIDParams struct {
	ID           pgtype.UUID `json:"id"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
}

type GetDietTagByIDRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
	Key  string      `json:"key"`
}

func (q *Queries) GetDietTagByID(ctx context.Context, arg GetDietTagByIDParams) (GetDietTagByIDRow, error) {
	row := q.db.QueryRow(ctx, getDietTagByID, arg.ID, arg.RestaurantID)
	var i GetDietTagByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.Key)
	return i, err
}

const getUserSubscriptionByUserID = `-- name: GetUserSubscriptionByUserID :one
SELECT id, stripe_subscription_id, stripe_customer_id, price_id, status, cancel_at_period_end
FROM user_subscriptions WHERE user_id = $1
`

type GetUserSubscriptionByUserIDRow struct {
	ID                   pgtype.UUID `json:"id"`
	StripeSubscriptionID string      `json:"stripe_subscription_id"`
	StripeCustomerID     string      `json:"stripe_customer_id"`
	PriceID              *string     `json:"price_id"`
	Status               *string     `json:"status"`
	CancelAtPeriodEnd    *bool       `json:"cancel_at_period_end"`
}

func (q *Queries) GetUserSubscriptionByUserID(ctx context.Context, userID pgtype.UUID) (GetUserSubscriptionByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getUserSubscriptionByUserID, userID)
	var i GetUserSubscriptionByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.StripeSubscriptionID,
		&i.StripeCustomerID,
		&i.PriceID,
		&i.Status,
		&i.CancelAtPeriodEnd,
	)
	return i, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (id, entity, entity_id, action, performed_by, before, after, restaurant_id, created_at)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5::jsonb, $6::jsonb, $7, now())
`

type InsertAuditLogParams struct {
	Entity       AuditEntity `json:"entity"`
	EntityID     pgtype.UUID `json:"entity_id"`
	Action       AuditAction `json:"action"`
	PerformedBy  pgtype.UUID `json:"performed_by"`
	Column5      []byte      `json:"column_5"`
	Column6      []byte      `json:"column_6"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.Entity,
		arg.EntityID,
		arg.Action,
		arg.PerformedBy,
		string(arg.Column5),
		string(arg.Column6),
		arg.RestaurantID,
	)
	return err
}

const listAddonsByRestaurant = `-- name: ListAddonsByRestaurant :many
SELECT id, name, price, translations, created_at
FROM addons WHERE restaurant_id = $1 ORDER BY created_at ASC
`

type ListAddonsByRestaurantRow struct {
	ID           pgtype.UUID      `json:"id"`
	Name         string           `json:"name"`
	Price        pgtype.Numeric   `json:"price"`
	Translations []byte           `json:"translations"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) ListAddonsByRestaurant(ctx context.Context, restaurantID pgtype.UUID) ([]ListAddonsByRestaurantRow, error) {
	rows, err := q.db.Query(ctx, listAddonsByRestaurant, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAddonsByRestaurantRow
	for rows.Next() {
		var i ListAddonsByRestaurantRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Translations,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT al.id, al.entity, al.entity_id, al.action, al.before, al.after, al.created_at,
       u.name AS user_name, u.email AS user_email, u.role AS user_role
FROM audit_logs al
LEFT JOIN users u ON u.id = al.performed_by
WHERE al.restaurant_id = $1
ORDER BY al.created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsParams struct {
	RestaurantID pgtype.UUID `json:"restaurant_id"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
}

type ListAuditLogsRow struct {
	ID        pgtype.UUID        `json:"id"`
	Entity    AuditEntity        `json:"entity"`
	EntityID  pgtype.UUID        `json:"entity_id"`
	Action    AuditAction        `json:"action"`
	Before    []byte             `json:"before"`
	After     []byte             `json:"after"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UserName  *string            `json:"user_name"`
	UserEmail *string            `json:"user_email"`
	UserRole  *string            `json:"user_role"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.RestaurantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogsRow
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.Entity,
			&i.EntityID,
			&i.Action,
			&i.Before,
			&i.After,
			&i.CreatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDietTagsForAdmin = `-- name: ListDietTagsForAdmin :many
SELECT id, name, key, translations, type, is_system, created_at
FROM tags WHERE restaurant_id = $1 AND type = 'diet' ORDER BY created_at DESC
`

type ListDietTagsForAdminRow struct {
	ID           pgtype.UUID      `json:"id"`
	Name         string           `json:"name"`
	Key          string           `json:"key"`
	Translations []byte           `json:"translations"`
	Type         TagType          `json:"type"`
	IsSystem     bool             `json:"is_system"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) ListDietTagsForAdmin(ctx context.Context, restaurantID pgtype.UUID) ([]ListDietTagsForAdminRow, error) {
	rows, err := q.db.Query(ctx, listDietTagsForAdmin, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDietTagsForAdminRow
	for rows.Next() {
		var i ListDietTagsForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Key,
			&i.Translations,
			&i.Type,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsForAdmin = `-- name: ListReviewsForAdmin :many
SELECT r.id, r.rating, r.comment, r.created_at, r.reviewable_id,
       mi.name AS item_name, mi.id AS item_id
FROM reviews r
LEFT JOIN menu_items mi ON mi.id = r.reviewable_id
WHERE r.restaurant_id = $1
ORDER BY r.created_at DESC
LIMIT $2 OFFSET $3
`

type ListReviewsForAdminParams struct {
	RestaurantID pgtype.UUID `json:"restaurant_id"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
}

type ListReviewsForAdminRow struct {
	ID           pgtype.UUID      `json:"id"`
	Rating       int32            `json:"rating"`
	Comment      string           `json:"comment"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	ReviewableID pgtype.UUID      `json:"reviewable_id"`
	ItemName     *string          `json:"item_name"`
	ItemID       pgtype.UUID      `json:"item_id"`
}

func (q *Queries) ListReviewsForAdmin(ctx context.Context, arg ListReviewsForAdminParams) ([]ListReviewsForAdminRow, error) {
	rows, err := q.db.Query(ctx, listReviewsForAdmin, arg.RestaurantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewsForAdminRow
	for rows.Next() {
		var i ListReviewsForAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
			&i.ReviewableID,
			&i.ItemName,
			&i.ItemID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionPlansWithStatus = `-- name: ListSubscriptionPlansWithStatus :many
SELECT sp.name, sp.product_id AS stripe_product_id, sp.price_id AS stripe_price_id,
       us.status, us.current_period_end, us.cancel_at_period_end
FROM subscriptions_plans sp
LEFT JOIN user_subscriptions us ON us.price_id = sp.price_id AND us.user_id = $1
`

type ListSubscriptionPlansWithStatusRow struct {
	Name              string           `json:"name"`
	StripeProductID   string           `json:"stripe_product_id"`
	StripePriceID     *string          `json:"stripe_price_id"`
	Status            *string          `json:"status"`
	CurrentPeriodEnd  pgtype.Timestamp `json:"current_period_end"`
	CancelAtPeriodEnd *bool            `json:"cancel_at_period_end"`
}

func (q *Queries) ListSubscriptionPlansWithStatus(ctx context.Context, userID pgtype.UUID) ([]ListSubscriptionPlansWithStatusRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptionPlansWithStatus, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubscriptionPlansWithStatusRow
	for rows.Next() {
		var i ListSubscriptionPlansWithStatusRow
		if err := rows.Scan(
			&i.Name,
			&i.StripeProductID,
			&i.StripePriceID,
			&i.Status,
			&i.CurrentPeriodEnd,
			&i.CancelAtPeriodEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monthlyCustomerCounts = `-- name: MonthlyCustomerCounts :many
SELECT DATE_TRUNC('month', created_at)::timestamp AS month, COUNT(*)::bigint AS count
FROM user_sessions
WHERE restaurant_id = $1
  AND ($2::timestamp IS NULL OR created_at >= $2)
  AND ($3::timestamp IS NULL OR created_at <= $3)
GROUP BY DATE_TRUNC('month', created_at)
ORDER BY DATE_TRUNC('month', created_at)
`

type MonthlyCustomerCountsParams struct {
	RestaurantID pgtype.UUID      `json:"restaurant_id"`
	Column2      pgtype.Timestamp `json:"column_2"`
	Column3      pgtype.Timestamp `json:"column_3"`
}

type MonthlyCustomerCountsRow struct {
	Month pgtype.Timestamp `json:"month"`
	Count int64            `json:"count"`
}

func (q *Queries) MonthlyCustomerCounts(ctx context.Context, arg MonthlyCustomerCountsParams) ([]MonthlyCustomerCountsRow, error) {
	rows, err := q.db.Query(ctx, monthlyCustomerCounts, arg.RestaurantID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MonthlyCustomerCountsRow
	for rows.Next() {
		var i MonthlyCustomerCountsRow
		if err := rows.Scan(&i.Month, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAddon = `-- name: UpdateAddon :exec
UPDATE addons SET name = COALESCE($1, name), price = COALESCE($2, price),
                  translation_status = 'pending'
WHERE id = $3 AND restaurant_id = $4
`

type UpdateAddonParams struct {
	Name         string         `json:"name"`
	Price        pgtype.Numeric `json:"price"`
	ID           pgtype.UUID    `json:"id"`
	RestaurantID pgtype.UUID    `json:"restaurant_id"`
}

func (q *Queries) UpdateAddon(ctx context.Context, arg UpdateAddonParams) error {
	_, err := q.db.Exec(ctx, updateAddon,
		arg.Name,
		arg.Price,
		arg.ID,
		arg.RestaurantID,
	)
	return err
}

const updateDietTag = `-- name: UpdateDietTag :exec
UPDATE tags SET name = lower($1), key = $2, translation_status = 'pending'
WHERE id = $3 AND type = 'diet' AND restaurant_id = $4 AND is_system = false
`

type UpdateDietTagParams struct {
	Lower        string      `json:"lower"`
	Key          string      `json:"key"`
	ID           pgtype.UUID `json:"id"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
}

func (q *Queries) UpdateDietTag(ctx context.Context, arg UpdateDietTagParams) error {
	_, err := q.db.Exec(ctx, updateDietTag,
		arg.Lower,
		arg.Key,
		arg.ID,
		arg.RestaurantID,
	)
	return err
}
