// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const banUser = `-- name: BanUser :exec
UPDATE users SET banned = $1, ban_reason = $2, ban_expires = $3, updated_at = now()
WHERE id = $4
`

type BanUserParams struct {
	Banned     *bool            `json:"banned"`
	BanReason  *string          `json:"ban_reason"`
	BanExpires pgtype.Timestamp `json:"ban_expires"`
	ID         pgtype.UUID      `json:"id"`
}

func (q *Queries) BanUser(ctx context.Context, arg BanUserParams) error {
	_, err := q.db.Exec(ctx, banUser,
		arg.Banned,
		arg.BanReason,
		arg.BanExpires,
		arg.ID,
	)
	return err
}

const createCredentialAccount = `-- name: CreateCredentialAccount :exec
INSERT INTO account (id, account_id, provider_id, user_id, password, created_at, updated_at)
VALUES (gen_random_uuid(), $1, 'credential', $2, $3, now(), now())
`

type CreateCredentialAccountParams struct {
	AccountID string      `json:"account_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Password  *string     `json:"password"`
}

func (q *Queries) CreateCredentialAccount(ctx context.Context, arg CreateCredentialAccountParams) error {
	_, err := q.db.Exec(ctx, createCredentialAccount, arg.AccountID, arg.UserID, arg.Password)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO session (id, expires_at, token, created_at, updated_at, ip_address, user_agent, user_id)
VALUES (gen_random_uuid(), $1, $2, now(), now(), $3, $4, $5)
RETURNING id, expires_at, token, created_at, updated_at, ip_address, user_agent, user_id, impersonated_by
`

type CreateSessionParams struct {
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	Token     string           `json:"token"`
	IpAddress *string          `json:"ip_address"`
	UserAgent *string          `json:"user_agent"`
	UserID    pgtype.UUID      `json:"user_id"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ExpiresAt,
		arg.Token,
		arg.IpAddress,
		arg.UserAgent,
		arg.UserID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ExpiresAt,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.UserID,
		&i.ImpersonatedBy,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, name, role, email_verified, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, $3, false, now(), now())
RETURNING id, email, name, role, restaurant_id, language_id, setup_complete,
          created_at, updated_at, email_verified, image, suspended, banned, ban_reason, ban_expires
`

type CreateUserParams struct {
	Email string  `json:"email"`
	Name  string  `json:"name"`
	Role  *string `json:"role"`
}

type CreateUserRow struct {
	ID            pgtype.UUID      `json:"id"`
	Email         string           `json:"email"`
	Name          string           `json:"name"`
	Role          *string          `json:"role"`
	RestaurantID  pgtype.UUID      `json:"restaurant_id"`
	LanguageID    pgtype.UUID      `json:"language_id"`
	SetupComplete *bool            `json:"setup_complete"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	EmailVerified bool             `json:"email_verified"`
	Image         *string          `json:"image"`
	Suspended     *bool            `json:"suspended"`
	Banned        *bool            `json:"banned"`
	BanReason     *string          `json:"ban_reason"`
	BanExpires    pgtype.Timestamp `json:"ban_expires"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Name, arg.Role)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.RestaurantID,
		&i.LanguageID,
		&i.SetupComplete,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerified,
		&i.Image,
		&i.Suspended,
		&i.Banned,
		&i.BanReason,
		&i.BanExpires,
	)
	return i, err
}

const createUserSession = `-- name: CreateUserSession :one
INSERT INTO user_sessions (id, restaurant_id, created_at)
VALUES (gen_random_uuid(), $1, now())
RETURNING id
`

func (q *Queries) CreateUserSession(ctx context.Context, restaurantID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createUserSession, restaurantID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createVerification = `-- name: CreateVerification :exec
INSERT INTO verification (id, identifier, value, expires_at, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, $3, now(), now())
`

type CreateVerificationParams struct {
	Identifier string           `json:"identifier"`
	Value      string           `json:"value"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateVerification(ctx context.Context, arg CreateVerificationParams) error {
	_, err := q.db.Exec(ctx, createVerification, arg.Identifier, arg.Value, arg.ExpiresAt)
	return err
}

const deleteSessionByToken = `-- name: DeleteSessionByToken :exec
DELETE FROM session WHERE token = $1
`

func (q *Queries) DeleteSessionByToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSessionByToken, token)
	return err
}

const deleteVerificationByIdentifier = `-- name: DeleteVerificationByIdentifier :exec
DELETE FROM verification WHERE identifier = $1
`

func (q *Queries) DeleteVerificationByIdentifier(ctx context.Context, identifier string) error {
	_, err := q.db.Exec(ctx, deleteVerificationByIdentifier, identifier)
	return err
}

const findCredentialAccount = `-- name: FindCredentialAccount :one
SELECT id, account_id, provider_id, user_id, password, created_at, updated_at
FROM account
WHERE user_id = $1 AND provider_id = 'credential'
LIMIT 1
`

type FindCredentialAccountRow struct {
	ID         pgtype.UUID      `json:"id"`
	AccountID  string           `json:"account_id"`
	ProviderID string           `json:"provider_id"`
	UserID     pgtype.UUID      `json:"user_id"`
	Password   *string          `json:"password"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) FindCredentialAccount(ctx context.Context, userID pgtype.UUID) (FindCredentialAccountRow, error) {
	row := q.db.QueryRow(ctx, findCredentialAccount, userID)
	var i FindCredentialAccountRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ProviderID,
		&i.UserID,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, email, name, role, restaurant_id, language_id, setup_complete,
       created_at, updated_at, email_verified, image, suspended, banned, ban_reason, ban_expires
FROM users
WHERE lower(email) = lower($1)
LIMIT 1
`

type FindUserByEmailRow struct {
	ID            pgtype.UUID      `json:"id"`
	Email         string           `json:"email"`
	Name          string           `json:"name"`
	Role          *string          `json:"role"`
	RestaurantID  pgtype.UUID      `json:"restaurant_id"`
	LanguageID    pgtype.UUID      `json:"language_id"`
	SetupComplete *bool            `json:"setup_complete"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	EmailVerified bool             `json:"email_verified"`
	Image         *string          `json:"image"`
	Suspended     *bool            `json:"suspended"`
	Banned        *bool            `json:"banned"`
	BanReason     *string          `json:"ban_reason"`
	BanExpires    pgtype.Timestamp `json:"ban_expires"`
}

func (q *Queries) FindUserByEmail(ctx context.Context, lower string) (FindUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, lower)
	var i FindUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.RestaurantID,
		&i.LanguageID,
		&i.SetupComplete,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerified,
		&i.Image,
		&i.Suspended,
		&i.Banned,
		&i.BanReason,
		&i.BanExpires,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, email, name, role, restaurant_id, language_id, setup_complete,
       created_at, updated_at, email_verified, image, suspended, banned, ban_reason, ban_expires
FROM users
WHERE id = $1
`

type FindUserByIDRow struct {
	ID            pgtype.UUID      `json:"id"`
	Email         string           `json:"email"`
	Name          string           `json:"name"`
	Role          *string          `json:"role"`
	RestaurantID  pgtype.UUID      `json:"restaurant_id"`
	LanguageID    pgtype.UUID      `json:"language_id"`
	SetupComplete *bool            `json:"setup_complete"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	EmailVerified bool             `json:"email_verified"`
	Image         *string          `json:"image"`
	Suspended     *bool            `json:"suspended"`
	Banned        *bool            `json:"banned"`
	BanReason     *string          `json:"ban_reason"`
	BanExpires    pgtype.Timestamp `json:"ban_expires"`
}

func (q *Queries) FindUserByID(ctx context.Context, id pgtype.UUID) (FindUserByIDRow, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i FindUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.RestaurantID,
		&i.LanguageID,
		&i.SetupComplete,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmailVerified,
		&i.Image,
		&i.Suspended,
		&i.Banned,
		&i.BanReason,
		&i.BanExpires,
	)
	return i, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, expires_at, token, created_at, updated_at, ip_address, user_agent, user_id, impersonated_by FROM session
WHERE token = $1 AND expires_at > now()
`

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, token)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ExpiresAt,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.UserID,
		&i.ImpersonatedBy,
	)
	return i, err
}

const getUserCurrency = `-- name: GetUserCurrency :one
SELECT c.id, c.code, c.name, c.symbol
FROM users u
JOIN restaurants r ON r.id = u.restaurant_id
JOIN currencies c ON c.id = r."currencyId"
WHERE u.id = $1
`

func (q *Queries) GetUserCurrency(ctx context.Context, id pgtype.UUID) (Currency, error) {
	row := q.db.QueryRow(ctx, getUserCurrency, id)
	var i Currency
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Symbol,
	)
	return i, err
}

const getUserSessionCurrency = `-- name: GetUserSessionCurrency :one
SELECT c.id, c.code, c.name, c.symbol
FROM user_sessions us
JOIN restaurants r ON r.id = us.restaurant_id
JOIN currencies c ON c.id = r."currencyId"
WHERE us.id = $1
`

func (q *Queries) GetUserSessionCurrency(ctx context.Context, id pgtype.UUID) (Currency, error) {
	row := q.db.QueryRow(ctx, getUserSessionCurrency, id)
	var i Currency
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Symbol,
	)
	return i, err
}

const getVerificationByIdentifier = `-- name: GetVerificationByIdentifier :one
SELECT id, identifier, value, expires_at, created_at, updated_at FROM verification
WHERE identifier = $1 AND expires_at > now()
`

func (q *Queries) GetVerificationByIdentifier(ctx context.Context, identifier string) (Verification, error) {
	row := q.db.QueryRow(ctx, getVerificationByIdentifier, identifier)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.Value,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isRestaurantSuspended = `-- name: IsRestaurantSuspended :one
SELECT r.suspended
FROM users u
JOIN restaurants r ON r.id = u.restaurant_id
WHERE u.id = $1
`

func (q *Queries) IsRestaurantSuspended(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isRestaurantSuspended, id)
	var suspended bool
	err := row.Scan(&suspended)
	return suspended, err
}

const setSessionImpersonatedBy = `-- name: SetSessionImpersonatedBy :exec
UPDATE session SET impersonated_by = $1, updated_at = now()
WHERE id = $2
`

type SetSessionImpersonatedByParams struct {
	ImpersonatedBy *string     `json:"impersonated_by"`
	ID             pgtype.UUID `json:"id"`
}

func (q *Queries) SetSessionImpersonatedBy(ctx context.Context, arg SetSessionImpersonatedByParams) error {
	_, err := q.db.Exec(ctx, setSessionImpersonatedBy, arg.ImpersonatedBy, arg.ID)
	return err
}

const updateAccountPassword = `-- name: UpdateAccountPassword :exec
UPDATE account SET password = $1, updated_at = now()
WHERE user_id = $2 AND provider_id = 'credential'
`

type UpdateAccountPasswordParams struct {
	Password *string     `json:"password"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateAccountPassword(ctx context.Context, arg UpdateAccountPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAccountPassword, arg.Password, arg.UserID)
	return err
}

const updateUserEmailVerified = `-- name: UpdateUserEmailVerified :exec
UPDATE users SET email_verified = true, updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateUserEmailVerified(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateUserEmailVerified, id)
	return err
}

const updateVerificationValue = `-- name: UpdateVerificationValue :exec
UPDATE verification SET value = $1, updated_at = now() WHERE identifier = $2
`

type UpdateVerificationValueParams struct {
	Value      string `json:"value"`
	Identifier string `json:"identifier"`
}

func (q *Queries) UpdateVerificationValue(ctx context.Context, arg UpdateVerificationValueParams) error {
	_, err := q.db.Exec(ctx, updateVerificationValue, arg.Value, arg.Identifier)
	return err
}
