// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bulk.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkInsertMenuItemAllergen = `-- name: BulkInsertMenuItemAllergen :exec
INSERT INTO menu_item_allergens (id, menu_item_id, allergen_id, severity)
VALUES (gen_random_uuid(), $1, $2, $3)
ON CONFLICT DO NOTHING
`

type BulkInsertMenuItemAllergenParams struct {
	MenuItemID pgtype.UUID `json:"menu_item_id"`
	AllergenID pgtype.UUID `json:"allergen_id"`
	Severity   *string     `json:"severity"`
}

func (q *Queries) BulkInsertMenuItemAllergen(ctx context.Context, arg BulkInsertMenuItemAllergenParams) error {
	_, err := q.db.Exec(ctx, bulkInsertMenuItemAllergen, arg.MenuItemID, arg.AllergenID, arg.Severity)
	return err
}

const findAddonByName = `-- name: FindAddonByName :one
SELECT id FROM addons WHERE lower(name) = lower($1) AND restaurant_id = $2 LIMIT 1
`

type FindAddonByNameParams struct {
	Lower        string      `json:"lower"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
}

func (q *Queries) FindAddonByName(ctx context.Context, arg FindAddonByNameParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findAddonByName, arg.Lower, arg.RestaurantID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const findAllergenByName = `-- name: FindAllergenByName :one
SELECT id FROM allergens WHERE lower(name) = lower($1) LIMIT 1
`

func (q *Queries) FindAllergenByName(ctx context.Context, lower string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findAllergenByName, lower)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const findDietTagByName = `-- name: FindDietTagByName :one
SELECT id FROM tags WHERE lower(name) = lower($1) AND type = 'diet' AND restaurant_id = $2 LIMIT 1
`

type FindDietTagByNameParams struct {
	Lower        string      `json:"lower"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
}

func (q *Queries) FindDietTagByName(ctx context.Context, arg FindDietTagByNameParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findDietTagByName, arg.Lower, arg.RestaurantID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const findMenuSectionByName = `-- name: FindMenuSectionByName :one
SELECT id FROM menu_sections WHERE lower(name) = lower($1) AND menu_id = $2 LIMIT 1
`

type FindMenuSectionByNameParams struct {
	Lower  string      `json:"lower"`
	MenuID pgtype.UUID `json:"menu_id"`
}

func (q *Queries) FindMenuSectionByName(ctx context.Context, arg FindMenuSectionByNameParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, findMenuSectionByName, arg.Lower, arg.MenuID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updateAddonTranslations = `-- name: UpdateAddonTranslations :exec
UPDATE addons SET translations = $1, translation_status = $2 WHERE id = $3
`

type UpdateAddonTranslationsParams struct {
	Translations      []byte      `json:"translations"`
	TranslationStatus *string     `json:"translation_status"`
	ID                pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAddonTranslations(ctx context.Context, arg UpdateAddonTranslationsParams) error {
	_, err := q.db.Exec(ctx, updateAddonTranslations, string(arg.Translations), arg.TranslationStatus, arg.ID)
	return err
}

const updateMenuItemTranslations = `-- name: UpdateMenuItemTranslations :exec
UPDATE menu_items SET translations = $1, translation_status = $2 WHERE id = $3
`

type UpdateMenuItemTranslationsParams struct {
	Translations      []byte      `json:"translations"`
	TranslationStatus *string     `json:"translation_status"`
	ID                pgtype.UUID `json:"id"`
}

// Translation update queries (called by the worker after DeepL)
func (q *Queries) UpdateMenuItemTranslations(ctx context.Context, arg UpdateMenuItemTranslationsParams) error {
	_, err := q.db.Exec(ctx, updateMenuItemTranslations, string(arg.Translations), arg.TranslationStatus, arg.ID)
	return err
}

const updateMenuItemVariantTranslations = `-- name: UpdateMenuItemVariantTranslations :exec
UPDATE menu_item_variants SET translations = $1, translation_status = $2 WHERE id = $3
`

type UpdateMenuItemVariantTranslationsParams struct {
	Translations      []byte      `json:"translations"`
	TranslationStatus *string     `json:"translation_status"`
	ID                pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateMenuItemVariantTranslations(ctx context.Context, arg UpdateMenuItemVariantTranslationsParams) error {
	_, err := q.db.Exec(ctx, updateMenuItemVariantTranslations, string(arg.Translations), arg.TranslationStatus, arg.ID)
	return err
}

const updateMenuSectionTranslations = `-- name: UpdateMenuSectionTranslations :exec
UPDATE menu_sections SET translations = $1, translation_status = $2 WHERE id = $3
`

type UpdateMenuSectionTranslationsParams struct {
	Translations      []byte      `json:"translations"`
	TranslationStatus *string     `json:"translation_status"`
	ID                pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateMenuSectionTranslations(ctx context.Context, arg UpdateMenuSectionTranslationsParams) error {
	_, err := q.db.Exec(ctx, updateMenuSectionTranslations, string(arg.Translations), arg.TranslationStatus, arg.ID)
	return err
}

const updateMenuTranslations = `-- name: UpdateMenuTranslations :exec
UPDATE menu SET translations = $1, translation_status = $2 WHERE id = $3
`

type UpdateMenuTranslationsParams struct {
	Translations      []byte      `json:"translations"`
	TranslationStatus *string     `json:"translation_status"`
	ID                pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateMenuTranslations(ctx context.Context, arg UpdateMenuTranslationsParams) error {
	_, err := q.db.Exec(ctx, updateMenuTranslations, string(arg.Translations), arg.TranslationStatus, arg.ID)
	return err
}

const updateTagTranslations = `-- name: UpdateTagTranslations :exec
UPDATE tags SET translations = $1, translation_status = $2 WHERE id = $3
`

type UpdateTagTranslationsParams struct {
	Translations      []byte             `json:"translations"`
	TranslationStatus *TranslationStatus `json:"translation_status"`
	ID                pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateTagTranslations(ctx context.Context, arg UpdateTagTranslationsParams) error {
	_, err := q.db.Exec(ctx, updateTagTranslations, string(arg.Translations), arg.TranslationStatus, arg.ID)
	return err
}
