// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: form_field_configs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFormFieldConfig = `-- name: GetFormFieldConfig :one
SELECT form_key, config, updated_at, updated_by
FROM form_field_configs
WHERE form_key = $1
`

type GetFormFieldConfigRow struct {
	FormKey   string             `json:"form_key"`
	Config    []byte             `json:"config"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
}

func (q *Queries) GetFormFieldConfig(ctx context.Context, formKey string) (GetFormFieldConfigRow, error) {
	row := q.db.QueryRow(ctx, getFormFieldConfig, formKey)
	var i GetFormFieldConfigRow
	err := row.Scan(
		&i.FormKey,
		&i.Config,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const upsertFormFieldConfig = `-- name: UpsertFormFieldConfig :exec
INSERT INTO form_field_configs (form_key, config, updated_at, updated_by)
VALUES ($1, $2::jsonb, now(), $3)
ON CONFLICT (form_key) DO UPDATE
  SET config = $2::jsonb, updated_at = now(), updated_by = $3
`

type UpsertFormFieldConfigParams struct {
	FormKey   string      `json:"form_key"`
	Column2   []byte      `json:"column_2"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpsertFormFieldConfig(ctx context.Context, arg UpsertFormFieldConfigParams) error {
	_, err := q.db.Exec(ctx, upsertFormFieldConfig, arg.FormKey, string(arg.Column2), arg.UpdatedBy)
	return err
}
