// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditAction string

const (
	AuditActionCREATE AuditAction = "CREATE"
	AuditActionUPDATE AuditAction = "UPDATE"
	AuditActionDELETE AuditAction = "DELETE"
)

func (e *AuditAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditAction(s)
	case string:
		*e = AuditAction(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditAction: %T", src)
	}
	return nil
}

type NullAuditAction struct {
	AuditAction AuditAction `json:"audit_action"`
	Valid       bool        `json:"valid"` // Valid is true if AuditAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditAction) Scan(value interface{}) error {
	if value == nil {
		ns.AuditAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditAction), nil
}

type AuditEntity string

const (
	AuditEntityMenu        AuditEntity = "menu"
	AuditEntityMenuItem    AuditEntity = "menu_item"
	AuditEntityMenuSection AuditEntity = "menu_section"
	AuditEntityUser        AuditEntity = "user"
	AuditEntityDiets       AuditEntity = "diets"
	AuditEntityAllergens   AuditEntity = "allergens"
	AuditEntityAddons      AuditEntity = "addons"
)

func (e *AuditEntity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditEntity(s)
	case string:
		*e = AuditEntity(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditEntity: %T", src)
	}
	return nil
}

type NullAuditEntity struct {
	AuditEntity AuditEntity `json:"audit_entity"`
	Valid       bool        `json:"valid"` // Valid is true if AuditEntity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditEntity) Scan(value interface{}) error {
	if value == nil {
		ns.AuditEntity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditEntity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditEntity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditEntity), nil
}

type RetaurantSetupStatus string

const (
	RetaurantSetupStatusPENDING   RetaurantSetupStatus = "PENDING"
	RetaurantSetupStatusCOMPLETED RetaurantSetupStatus = "COMPLETED"
	RetaurantSetupStatusRELEASED  RetaurantSetupStatus = "RELEASED"
)

func (e *RetaurantSetupStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RetaurantSetupStatus(s)
	case string:
		*e = RetaurantSetupStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RetaurantSetupStatus: %T", src)
	}
	return nil
}

type NullRetaurantSetupStatus struct {
	RetaurantSetupStatus RetaurantSetupStatus `json:"retaurantSetupStatus"`
	Valid                bool                 `json:"valid"` // Valid is true if RetaurantSetupStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRetaurantSetupStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RetaurantSetupStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RetaurantSetupStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRetaurantSetupStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RetaurantSetupStatus), nil
}

type SetupStatus string

const (
	SetupStatusPENDING   SetupStatus = "PENDING"
	SetupStatusCOMPLETED SetupStatus = "COMPLETED"
)

func (e *SetupStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SetupStatus(s)
	case string:
		*e = SetupStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SetupStatus: %T", src)
	}
	return nil
}

type NullSetupStatus struct {
	SetupStatus SetupStatus `json:"setup_status"`
	Valid       bool        `json:"valid"` // Valid is true if SetupStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSetupStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SetupStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SetupStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSetupStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SetupStatus), nil
}

type SpiceLevel string

const (
	SpiceLevelValue0    SpiceLevel = ""
	SpiceLevelMild      SpiceLevel = "mild"
	SpiceLevelMedium    SpiceLevel = "medium"
	SpiceLevelSpicy     SpiceLevel = "spicy"
	SpiceLevelVerySpicy SpiceLevel = "very_spicy"
)

func (e *SpiceLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SpiceLevel(s)
	case string:
		*e = SpiceLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for SpiceLevel: %T", src)
	}
	return nil
}

type NullSpiceLevel struct {
	SpiceLevel SpiceLevel `json:"spice_level"`
	Valid      bool       `json:"valid"` // Valid is true if SpiceLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSpiceLevel) Scan(value interface{}) error {
	if value == nil {
		ns.SpiceLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SpiceLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSpiceLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SpiceLevel), nil
}

type TagType string

const (
	TagTypeDiet      TagType = "diet"
	TagTypeCuisine   TagType = "cuisine"
	TagTypeDishType  TagType = "dish_type"
	TagTypeAllergen  TagType = "allergen"
	TagTypeDrinkType TagType = "drink_type"
)

func (e *TagType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TagType(s)
	case string:
		*e = TagType(s)
	default:
		return fmt.Errorf("unsupported scan type for TagType: %T", src)
	}
	return nil
}

type NullTagType struct {
	TagType TagType `json:"tag_type"`
	Valid   bool    `json:"valid"` // Valid is true if TagType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTagType) Scan(value interface{}) error {
	if value == nil {
		ns.TagType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TagType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTagType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TagType), nil
}

type TranslationStatus string

const (
	TranslationStatusPending   TranslationStatus = "pending"
	TranslationStatusCompleted TranslationStatus = "completed"
	TranslationStatusFailed    TranslationStatus = "failed"
)

func (e *TranslationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TranslationStatus(s)
	case string:
		*e = TranslationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TranslationStatus: %T", src)
	}
	return nil
}

type NullTranslationStatus struct {
	TranslationStatus TranslationStatus `json:"translation_status"`
	Valid             bool              `json:"valid"` // Valid is true if TranslationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTranslationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TranslationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TranslationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTranslationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TranslationStatus), nil
}

type Account struct {
	ID                    pgtype.UUID      `json:"id"`
	AccountID             string           `json:"account_id"`
	ProviderID            string           `json:"provider_id"`
	UserID                pgtype.UUID      `json:"user_id"`
	AccessToken           *string          `json:"access_token"`
	RefreshToken          *string          `json:"refresh_token"`
	IDToken               *string          `json:"id_token"`
	AccessTokenExpiresAt  pgtype.Timestamp `json:"access_token_expires_at"`
	RefreshTokenExpiresAt pgtype.Timestamp `json:"refresh_token_expires_at"`
	Scope                 *string          `json:"scope"`
	Password              *string          `json:"password"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
}

type Addon struct {
	ID                pgtype.UUID      `json:"id"`
	RestaurantID      pgtype.UUID      `json:"restaurant_id"`
	Name              string           `json:"name"`
	Translations      []byte           `json:"translations"`
	TranslationStatus *string          `json:"translation_status"`
	Price             pgtype.Numeric   `json:"price"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
}

type AiUsageLog struct {
	ID             pgtype.UUID      `json:"id"`
	SessionID      string           `json:"session_id"`
	SubscriptionID string           `json:"subscription_id"`
	UsedTokens     int32            `json:"used_tokens"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	RestaurantID   pgtype.UUID      `json:"restaurant_id"`
}

type Allergen struct {
	ID                pgtype.UUID      `json:"id"`
	Name              string           `json:"name"`
	Translations      []byte           `json:"translations"`
	TranslationStatus *string          `json:"translation_status"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
}

type AuditLog struct {
	ID           pgtype.UUID        `json:"id"`
	Entity       AuditEntity        `json:"entity"`
	EntityID     pgtype.UUID        `json:"entity_id"`
	Action       AuditAction        `json:"action"`
	PerformedBy  pgtype.UUID        `json:"performed_by"`
	Before       []byte             `json:"before"`
	After        []byte             `json:"after"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	RestaurantID pgtype.UUID        `json:"restaurant_id"`
}

type Currency struct {
	ID     pgtype.UUID `json:"id"`
	Code   string      `json:"code"`
	Name   string      `json:"name"`
	Symbol string      `json:"symbol"`
}

type Language struct {
	ID        pgtype.UUID `json:"id"`
	Code      string      `json:"code"`
	Name      string      `json:"name"`
	Flag      *string     `json:"flag"`
	IsActive  *bool       `json:"is_active"`
	SortOrder *int32      `json:"sort_order"`
}

type Menu struct {
	ID                pgtype.UUID      `json:"id"`
	RestaurantID      pgtype.UUID      `json:"restaurant_id"`
	Name              string           `json:"name"`
	Description       *string          `json:"description"`
	Translations      []byte           `json:"translations"`
	TranslationStatus *string          `json:"translation_status"`
	Active            *bool            `json:"active"`
	StartTime         *string          `json:"start_time"`
	EndTime           *string          `json:"end_time"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
}

type MenuItem struct {
	ID                 pgtype.UUID      `json:"id"`
	SectionID          pgtype.UUID      `json:"section_id"`
	RestaurantID       pgtype.UUID      `json:"restaurant_id"`
	Type               string           `json:"type"`
	Name               string           `json:"name"`
	Description        *string          `json:"description"`
	Translations       []byte           `json:"translations"`
	TranslationStatus  *string          `json:"translation_status"`
	Ingredients        []string         `json:"ingredients"`
	Images             []string         `json:"images"`
	Price              pgtype.Numeric   `json:"price"`
	DiscountType       *string          `json:"discount_type"`
	DiscountValue      pgtype.Numeric   `json:"discount_value"`
	DiscountStartAt    pgtype.Timestamp `json:"discount_start_at"`
	DiscountEndAt      pgtype.Timestamp `json:"discount_end_at"`
	DiscountLabel      *string          `json:"discount_label"`
	IsAvailable        *bool            `json:"is_available"`
	SpiceLevel         *SpiceLevel      `json:"spice_level"`
	CookTime           *int32           `json:"cook_time"`
	IsAlcoholic        *bool            `json:"is_alcoholic"`
	HasVariants        *bool            `json:"has_variants"`
	IsChefsRecommended *bool            `json:"is_chefs_recommended"`
	IsPopular          *bool            `json:"is_popular"`
	IsNew              *bool            `json:"is_new"`
	IsLimitedTime      *bool            `json:"is_limited_time"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}

type MenuItemAddon struct {
	ItemID  pgtype.UUID `json:"item_id"`
	AddonID pgtype.UUID `json:"addon_id"`
}

type MenuItemAllergen struct {
	ID         pgtype.UUID `json:"id"`
	MenuItemID pgtype.UUID `json:"menu_item_id"`
	AllergenID pgtype.UUID `json:"allergen_id"`
	Severity   *string     `json:"severity"`
}

type MenuItemTag struct {
	ID         pgtype.UUID `json:"id"`
	MenuItemID pgtype.UUID `json:"menu_item_id"`
	TagID      pgtype.UUID `json:"tag_id"`
}

type MenuItemUnitsNew struct {
	ID                pgtype.UUID      `json:"id"`
	Name              string           `json:"name"`
	Translations      []byte           `json:"translations"`
	TranslationStatus *string          `json:"translation_status"`
	Symbol            *string          `json:"symbol"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
}

type MenuItemVariant struct {
	ID                pgtype.UUID      `json:"id"`
	ItemID            pgtype.UUID      `json:"item_id"`
	Translations      []byte           `json:"translations"`
	TranslationStatus *string          `json:"translation_status"`
	Name              string           `json:"name"`
	Price             pgtype.Numeric   `json:"price"`
	IsAvailable       *bool            `json:"is_available"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
}

type MenuSection struct {
	ID                pgtype.UUID      `json:"id"`
	MenuID            pgtype.UUID      `json:"menu_id"`
	Name              string           `json:"name"`
	Description       *string          `json:"description"`
	Translations      []byte           `json:"translations"`
	TranslationStatus *string          `json:"translation_status"`
	SortOrder         *int32           `json:"sort_order"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
}

type PasskeyCredential struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	CredentialID string             `json:"credential_id"`
	PublicKey    []byte             `json:"public_key"`
	SignCount    int64              `json:"sign_count"`
	Aaguid       string             `json:"aaguid"`
	DeviceName   string             `json:"device_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type PendingStripeEvent struct {
	ID         pgtype.UUID      `json:"id"`
	EventID    string           `json:"event_id"`
	EventType  string           `json:"event_type"`
	RelatedID  *string          `json:"related_id"`
	Payload    string           `json:"payload"`
	ReceivedAt pgtype.Timestamp `json:"received_at"`
}

type Restaurant struct {
	ID              pgtype.UUID           `json:"id"`
	Name            *string               `json:"name"`
	Address         *string               `json:"address"`
	Phone           *string               `json:"phone"`
	Website         *string               `json:"website"`
	Image           *string               `json:"image"`
	BannerUrl       *string               `json:"banner_url"`
	Description     *string               `json:"description"`
	Color           *string               `json:"color"`
	CreatedAt       pgtype.Timestamp      `json:"created_at"`
	CurrencyId      pgtype.UUID           `json:"currencyId"`
	Status          *RetaurantSetupStatus `json:"status"`
	AdminEmail      *string               `json:"admin_email"`
	Suspended       bool                  `json:"suspended"`
	SuspendedAt     pgtype.Timestamp      `json:"suspended_at"`
	SuspendedReason *string               `json:"suspended_reason"`
	SuspendedBy     pgtype.UUID           `json:"suspended_by"`
	Slug            *string               `json:"slug"`
}

type Review struct {
	ID           pgtype.UUID      `json:"id"`
	ReviewableID pgtype.UUID      `json:"reviewable_id"`
	Rating       int32            `json:"rating"`
	Comment      string           `json:"comment"`
	Email        *string          `json:"email"`
	RestaurantID pgtype.UUID      `json:"restaurant_id"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
}

type Session struct {
	ID             pgtype.UUID      `json:"id"`
	ExpiresAt      pgtype.Timestamp `json:"expires_at"`
	Token          string           `json:"token"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	IpAddress      *string          `json:"ip_address"`
	UserAgent      *string          `json:"user_agent"`
	UserID         pgtype.UUID      `json:"user_id"`
	ImpersonatedBy *string          `json:"impersonated_by"`
}

type SessionTag struct {
	SessionID pgtype.UUID `json:"session_id"`
	TagID     pgtype.UUID `json:"tag_id"`
}

type SubscriptionsPlan struct {
	ID        pgtype.UUID      `json:"id"`
	ProductID string           `json:"product_id"`
	Name      string           `json:"name"`
	PriceID   *string          `json:"price_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Tag struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	Key               string             `json:"key"`
	Type              TagType            `json:"type"`
	IsSystem          bool               `json:"is_system"`
	Description       *string            `json:"description"`
	Translations      []byte             `json:"translations"`
	TranslationStatus *TranslationStatus `json:"translation_status"`
	RestaurantID      pgtype.UUID        `json:"restaurant_id"`
	CreatedAt         pgtype.Timestamp   `json:"created_at"`
}

type User struct {
	ID            pgtype.UUID      `json:"id"`
	Email         string           `json:"email"`
	Name          string           `json:"name"`
	RestaurantID  pgtype.UUID      `json:"restaurant_id"`
	LanguageID    pgtype.UUID      `json:"language_id"`
	SetupComplete *bool            `json:"setup_complete"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	Suspended     *bool            `json:"suspended"`
	Role          *string          `json:"role"`
	EmailVerified bool             `json:"email_verified"`
	Image         *string          `json:"image"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	Banned        *bool            `json:"banned"`
	BanReason     *string          `json:"ban_reason"`
	BanExpires    pgtype.Timestamp `json:"ban_expires"`
}

type UserSession struct {
	ID                      pgtype.UUID      `json:"id"`
	RestaurantID            pgtype.UUID      `json:"restaurant_id"`
	CreatedAt               pgtype.Timestamp `json:"created_at"`
	PreferenceSetupComplete *bool            `json:"preference_setup_complete"`
}

type UserSessionAllergen struct {
	SessionID  pgtype.UUID `json:"session_id"`
	AllergenID pgtype.UUID `json:"allergen_id"`
}

type UserSessionTag struct {
	SessionID pgtype.UUID `json:"session_id"`
	TagID     pgtype.UUID `json:"tag_id"`
}

type UserSubscription struct {
	ID                   pgtype.UUID      `json:"id"`
	UserID               pgtype.UUID      `json:"user_id"`
	StripeSubscriptionID string           `json:"stripe_subscription_id"`
	StripeCustomerID     string           `json:"stripe_customer_id"`
	PriceID              *string          `json:"price_id"`
	Status               *string          `json:"status"`
	CancelAtPeriodEnd    *bool            `json:"cancel_at_period_end"`
	CurrentPeriodStart   pgtype.Timestamp `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamp `json:"current_period_end"`
	CanceledAt           pgtype.Timestamp `json:"canceled_at"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
	PlanID               pgtype.UUID      `json:"plan_id"`
	Canceled             *bool            `json:"canceled"`
}

type Verification struct {
	ID         pgtype.UUID      `json:"id"`
	Identifier string           `json:"identifier"`
	Value      string           `json:"value"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}
