// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: passkey.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPasskeyCredentials = `-- name: CountPasskeyCredentials :one
SELECT COUNT(*) FROM passkey_credentials WHERE user_id = $1
`

func (q *Queries) CountPasskeyCredentials(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPasskeyCredentials, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePasskeyCredential = `-- name: DeletePasskeyCredential :exec
DELETE FROM passkey_credentials WHERE credential_id = $1 AND user_id = $2
`

type DeletePasskeyCredentialParams struct {
	CredentialID string      `json:"credential_id"`
	UserID       pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeletePasskeyCredential(ctx context.Context, arg DeletePasskeyCredentialParams) error {
	_, err := q.db.Exec(ctx, deletePasskeyCredential, arg.CredentialID, arg.UserID)
	return err
}

const getPasskeyCredentialByCredID = `-- name: GetPasskeyCredentialByCredID :one
SELECT id, user_id, credential_id, public_key, sign_count, aaguid, device_name, created_at FROM passkey_credentials WHERE credential_id = $1
`

func (q *Queries) GetPasskeyCredentialByCredID(ctx context.Context, credentialID string) (PasskeyCredential, error) {
	row := q.db.QueryRow(ctx, getPasskeyCredentialByCredID, credentialID)
	var i PasskeyCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.SignCount,
		&i.Aaguid,
		&i.DeviceName,
		&i.CreatedAt,
	)
	return i, err
}

const insertPasskeyCredential = `-- name: InsertPasskeyCredential :one
INSERT INTO passkey_credentials (user_id, credential_id, public_key, sign_count, aaguid, device_name)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, credential_id, public_key, sign_count, aaguid, device_name, created_at
`

type InsertPasskeyCredentialParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	CredentialID string      `json:"credential_id"`
	PublicKey    []byte      `json:"public_key"`
	SignCount    int64       `json:"sign_count"`
	Aaguid       string      `json:"aaguid"`
	DeviceName   string      `json:"device_name"`
}

func (q *Queries) InsertPasskeyCredential(ctx context.Context, arg InsertPasskeyCredentialParams) (PasskeyCredential, error) {
	row := q.db.QueryRow(ctx, insertPasskeyCredential,
		arg.UserID,
		arg.CredentialID,
		arg.PublicKey,
		arg.SignCount,
		arg.Aaguid,
		arg.DeviceName,
	)
	var i PasskeyCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.SignCount,
		&i.Aaguid,
		&i.DeviceName,
		&i.CreatedAt,
	)
	return i, err
}

const listPasskeyCredentials = `-- name: ListPasskeyCredentials :many
SELECT id, user_id, credential_id, public_key, sign_count, aaguid, device_name, created_at FROM passkey_credentials WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListPasskeyCredentials(ctx context.Context, userID pgtype.UUID) ([]PasskeyCredential, error) {
	rows, err := q.db.Query(ctx, listPasskeyCredentials, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PasskeyCredential
	for rows.Next() {
		var i PasskeyCredential
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CredentialID,
			&i.PublicKey,
			&i.SignCount,
			&i.Aaguid,
			&i.DeviceName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePasskeySignCount = `-- name: UpdatePasskeySignCount :exec
UPDATE passkey_credentials SET sign_count = $1 WHERE credential_id = $2
`

type UpdatePasskeySignCountParams struct {
	SignCount    int64  `json:"sign_count"`
	CredentialID string `json:"credential_id"`
}

func (q *Queries) UpdatePasskeySignCount(ctx context.Context, arg UpdatePasskeySignCountParams) error {
	_, err := q.db.Exec(ctx, updatePasskeySignCount, arg.SignCount, arg.CredentialID)
	return err
}
