// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: super.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const aIUsageChartForRestaurant = `-- name: AIUsageChartForRestaurant :many
SELECT COUNT(id)::bigint AS count,
       DATE_TRUNC('month', created_at)::timestamp AS month
FROM ai_usage_logs
WHERE restaurant_id = $1
GROUP BY DATE_TRUNC('month', created_at)
ORDER BY month
`

type AIUsageChartForRestaurantRow struct {
	Count int64            `json:"count"`
	Month pgtype.Timestamp `json:"month"`
}

func (q *Queries) AIUsageChartForRestaurant(ctx context.Context, restaurantID pgtype.UUID) ([]AIUsageChartForRestaurantRow, error) {
	rows, err := q.db.Query(ctx, aIUsageChartForRestaurant, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AIUsageChartForRestaurantRow
	for rows.Next() {
		var i AIUsageChartForRestaurantRow
		if err := rows.Scan(&i.Count, &i.Month); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countRestaurantsForSuper = `-- name: CountRestaurantsForSuper :one
SELECT COUNT(*) FROM restaurants
WHERE ($1 = '' OR lower(name) LIKE lower($1))
  AND ($2 = '' OR status::text = $2)
`

type CountRestaurantsForSuperParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) CountRestaurantsForSuper(ctx context.Context, arg CountRestaurantsForSuperParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRestaurantsForSuper, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReviewsForRestaurant = `-- name: CountReviewsForRestaurant :one
SELECT COUNT(*) FROM reviews WHERE restaurant_id = $1
`

func (q *Queries) CountReviewsForRestaurant(ctx context.Context, restaurantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countReviewsForRestaurant, restaurantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubscriptionsForSuper = `-- name: CountSubscriptionsForSuper :one
SELECT COUNT(*) FROM user_subscriptions
`

func (q *Queries) CountSubscriptionsForSuper(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSubscriptionsForSuper)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserSessionsForRestaurant = `-- name: CountUserSessionsForRestaurant :one
SELECT COUNT(*) FROM user_sessions WHERE restaurant_id = $1
`

func (q *Queries) CountUserSessionsForRestaurant(ctx context.Context, restaurantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserSessionsForRestaurant, restaurantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO users (id, email, name, role, restaurant_id, email_verified, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, 'user', $3, true, now(), now())
RETURNING id
`

type CreateAdminUserParams struct {
	Email        string      `json:"email"`
	Name         string      `json:"name"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createAdminUser, arg.Email, arg.Name, arg.RestaurantID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createAllergen = `-- name: CreateAllergen :one
INSERT INTO allergens (id, name, created_at)
VALUES (gen_random_uuid(), $1, now())
RETURNING id
`

func (q *Queries) CreateAllergen(ctx context.Context, name string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createAllergen, name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createRestaurantForSuper = `-- name: CreateRestaurantForSuper :one
INSERT INTO restaurants (id, name, "currencyId", admin_email, status, created_at)
VALUES (gen_random_uuid(), $1, $2, $3, 'PENDING', now())
RETURNING id
`

type CreateRestaurantForSuperParams struct {
	Name       *string     `json:"name"`
	CurrencyId pgtype.UUID `json:"currencyId"`
	AdminEmail *string     `json:"admin_email"`
}

func (q *Queries) CreateRestaurantForSuper(ctx context.Context, arg CreateRestaurantForSuperParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createRestaurantForSuper, arg.Name, arg.CurrencyId, arg.AdminEmail)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createSuperAdminUser = `-- name: CreateSuperAdminUser :one
INSERT INTO users (id, email, name, role, email_verified, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, 'admin', true, now(), now())
RETURNING id
`

type CreateSuperAdminUserParams struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

func (q *Queries) CreateSuperAdminUser(ctx context.Context, arg CreateSuperAdminUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createSuperAdminUser, arg.Email, arg.Name)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteAllergen = `-- name: DeleteAllergen :exec
DELETE FROM allergens WHERE id = $1
`

func (q *Queries) DeleteAllergen(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllergen, id)
	return err
}

const deletePendingStripeEvent = `-- name: DeletePendingStripeEvent :exec
DELETE FROM pending_stripe_events WHERE id = $1
`

func (q *Queries) DeletePendingStripeEvent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePendingStripeEvent, id)
	return err
}

const deleteRestaurantByID = `-- name: DeleteRestaurantByID :exec
DELETE FROM restaurants WHERE id = $1
`

func (q *Queries) DeleteRestaurantByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRestaurantByID, id)
	return err
}

const deleteSubscriptionPlan = `-- name: DeleteSubscriptionPlan :exec
DELETE FROM subscriptions_plans WHERE product_id = $1
`

func (q *Queries) DeleteSubscriptionPlan(ctx context.Context, productID string) error {
	_, err := q.db.Exec(ctx, deleteSubscriptionPlan, productID)
	return err
}

const getPlanByPriceID = `-- name: GetPlanByPriceID :one
SELECT id FROM subscriptions_plans WHERE price_id = $1
`

func (q *Queries) GetPlanByPriceID(ctx context.Context, priceID *string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getPlanByPriceID, priceID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getPlanByProductID = `-- name: GetPlanByProductID :one
SELECT id, price_id FROM subscriptions_plans WHERE product_id = $1
`

type GetPlanByProductIDRow struct {
	ID      pgtype.UUID `json:"id"`
	PriceID *string     `json:"price_id"`
}

func (q *Queries) GetPlanByProductID(ctx context.Context, productID string) (GetPlanByProductIDRow, error) {
	row := q.db.QueryRow(ctx, getPlanByProductID, productID)
	var i GetPlanByProductIDRow
	err := row.Scan(&i.ID, &i.PriceID)
	return i, err
}

const getRestaurantBySlug = `-- name: GetRestaurantBySlug :one
SELECT id, name, slug, image FROM restaurants WHERE slug = $1
`

type GetRestaurantBySlugRow struct {
	ID    pgtype.UUID `json:"id"`
	Name  *string     `json:"name"`
	Slug  *string     `json:"slug"`
	Image *string     `json:"image"`
}

func (q *Queries) GetRestaurantBySlug(ctx context.Context, slug *string) (GetRestaurantBySlugRow, error) {
	row := q.db.QueryRow(ctx, getRestaurantBySlug, slug)
	var i GetRestaurantBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Image,
	)
	return i, err
}

const getRestaurantDetailForSuper = `-- name: GetRestaurantDetailForSuper :one
SELECT id, name, address, image, description, status, admin_email, suspended,
       suspended_reason, suspended_at, "currencyId" AS currency_id, created_at
FROM restaurants WHERE id = $1
`

type GetRestaurantDetailForSuperRow struct {
	ID              pgtype.UUID           `json:"id"`
	Name            *string               `json:"name"`
	Address         *string               `json:"address"`
	Image           *string               `json:"image"`
	Description     *string               `json:"description"`
	Status          *RetaurantSetupStatus `json:"status"`
	AdminEmail      *string               `json:"admin_email"`
	Suspended       bool                  `json:"suspended"`
	SuspendedReason *string               `json:"suspended_reason"`
	SuspendedAt     pgtype.Timestamp      `json:"suspended_at"`
	CurrencyID      pgtype.UUID           `json:"currency_id"`
	CreatedAt       pgtype.Timestamp      `json:"created_at"`
}

func (q *Queries) GetRestaurantDetailForSuper(ctx context.Context, id pgtype.UUID) (GetRestaurantDetailForSuperRow, error) {
	row := q.db.QueryRow(ctx, getRestaurantDetailForSuper, id)
	var i GetRestaurantDetailForSuperRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Image,
		&i.Description,
		&i.Status,
		&i.AdminEmail,
		&i.Suspended,
		&i.SuspendedReason,
		&i.SuspendedAt,
		&i.CurrencyID,
		&i.CreatedAt,
	)
	return i, err
}

const getSubscriptionByStripeID = `-- name: GetSubscriptionByStripeID :one
SELECT id, user_id FROM user_subscriptions WHERE stripe_subscription_id = $1
`

type GetSubscriptionByStripeIDRow struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetSubscriptionByStripeID(ctx context.Context, stripeSubscriptionID string) (GetSubscriptionByStripeIDRow, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByStripeID, stripeSubscriptionID)
	var i GetSubscriptionByStripeIDRow
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}

const getSubscriptionByUserID = `-- name: GetSubscriptionByUserID :one
SELECT id, stripe_subscription_id, status FROM user_subscriptions WHERE user_id = $1
`

type GetSubscriptionByUserIDRow struct {
	ID                   pgtype.UUID `json:"id"`
	StripeSubscriptionID string      `json:"stripe_subscription_id"`
	Status               *string     `json:"status"`
}

func (q *Queries) GetSubscriptionByUserID(ctx context.Context, userID pgtype.UUID) (GetSubscriptionByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByUserID, userID)
	var i GetSubscriptionByUserIDRow
	err := row.Scan(&i.ID, &i.StripeSubscriptionID, &i.Status)
	return i, err
}

const getUserByEmailForSuper = `-- name: GetUserByEmailForSuper :one
SELECT id, email, name FROM users WHERE email = $1
`

type GetUserByEmailForSuperRow struct {
	ID    pgtype.UUID `json:"id"`
	Email string      `json:"email"`
	Name  string      `json:"name"`
}

func (q *Queries) GetUserByEmailForSuper(ctx context.Context, email string) (GetUserByEmailForSuperRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmailForSuper, email)
	var i GetUserByEmailForSuperRow
	err := row.Scan(&i.ID, &i.Email, &i.Name)
	return i, err
}

const insertPendingStripeEvent = `-- name: InsertPendingStripeEvent :exec
INSERT INTO pending_stripe_events (id, event_id, event_type, related_id, payload, received_at)
VALUES (gen_random_uuid(), $1, $2, $3, $4, now())
ON CONFLICT (event_id) DO NOTHING
`

type InsertPendingStripeEventParams struct {
	EventID   string  `json:"event_id"`
	EventType string  `json:"event_type"`
	RelatedID *string `json:"related_id"`
	Payload   string  `json:"payload"`
}

func (q *Queries) InsertPendingStripeEvent(ctx context.Context, arg InsertPendingStripeEventParams) error {
	_, err := q.db.Exec(ctx, insertPendingStripeEvent,
		arg.EventID,
		arg.EventType,
		arg.RelatedID,
		arg.Payload,
	)
	return err
}

const listActiveSubscriptions = `-- name: ListActiveSubscriptions :many
SELECT id, stripe_subscription_id, status FROM user_subscriptions WHERE status = 'active'
`

type ListActiveSubscriptionsRow struct {
	ID                   pgtype.UUID `json:"id"`
	StripeSubscriptionID string      `json:"stripe_subscription_id"`
	Status               *string     `json:"status"`
}

func (q *Queries) ListActiveSubscriptions(ctx context.Context) ([]ListActiveSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listActiveSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveSubscriptionsRow
	for rows.Next() {
		var i ListActiveSubscriptionsRow
		if err := rows.Scan(&i.ID, &i.StripeSubscriptionID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingStripeEvents = `-- name: ListPendingStripeEvents :many
SELECT id, event_id, event_type, related_id, payload FROM pending_stripe_events
ORDER BY received_at
`

type ListPendingStripeEventsRow struct {
	ID        pgtype.UUID `json:"id"`
	EventID   string      `json:"event_id"`
	EventType string      `json:"event_type"`
	RelatedID *string     `json:"related_id"`
	Payload   string      `json:"payload"`
}

func (q *Queries) ListPendingStripeEvents(ctx context.Context) ([]ListPendingStripeEventsRow, error) {
	rows, err := q.db.Query(ctx, listPendingStripeEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingStripeEventsRow
	for rows.Next() {
		var i ListPendingStripeEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventType,
			&i.RelatedID,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRestaurantsForSuper = `-- name: ListRestaurantsForSuper :many
SELECT id, name, address, image, description, status, admin_email, suspended,
       "currencyId" AS currency_id, created_at
FROM restaurants
WHERE ($1 = '' OR lower(name) LIKE lower($1))
  AND ($2 = '' OR status::text = $2)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListRestaurantsForSuperParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListRestaurantsForSuperRow struct {
	ID          pgtype.UUID           `json:"id"`
	Name        *string               `json:"name"`
	Address     *string               `json:"address"`
	Image       *string               `json:"image"`
	Description *string               `json:"description"`
	Status      *RetaurantSetupStatus `json:"status"`
	AdminEmail  *string               `json:"admin_email"`
	Suspended   bool                  `json:"suspended"`
	CurrencyID  pgtype.UUID           `json:"currency_id"`
	CreatedAt   pgtype.Timestamp      `json:"created_at"`
}

func (q *Queries) ListRestaurantsForSuper(ctx context.Context, arg ListRestaurantsForSuperParams) ([]ListRestaurantsForSuperRow, error) {
	rows, err := q.db.Query(ctx, listRestaurantsForSuper,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRestaurantsForSuperRow
	for rows.Next() {
		var i ListRestaurantsForSuperRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Image,
			&i.Description,
			&i.Status,
			&i.AdminEmail,
			&i.Suspended,
			&i.CurrencyID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionPlans = `-- name: ListSubscriptionPlans :many
SELECT name FROM subscriptions_plans ORDER BY name
`

func (q *Queries) ListSubscriptionPlans(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listSubscriptionPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsForSuper = `-- name: ListSubscriptionsForSuper :many
SELECT us.status, us.stripe_subscription_id, us.current_period_start, us.current_period_end,
       u.name AS user_name, r.name AS restaurant_name, sp.name AS plan_name
FROM user_subscriptions us
LEFT JOIN users u ON us.user_id = u.id
LEFT JOIN restaurants r ON u.restaurant_id = r.id
LEFT JOIN subscriptions_plans sp ON sp.id = us.plan_id
WHERE ($1 = '' OR lower(r.name) LIKE lower($1))
  AND ($2 = '' OR sp.name = $2)
ORDER BY us.created_at DESC
LIMIT $3 OFFSET $4
`

type ListSubscriptionsForSuperParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListSubscriptionsForSuperRow struct {
	Status               *string          `json:"status"`
	StripeSubscriptionID string           `json:"stripe_subscription_id"`
	CurrentPeriodStart   pgtype.Timestamp `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamp `json:"current_period_end"`
	UserName             *string          `json:"user_name"`
	RestaurantName       *string          `json:"restaurant_name"`
	PlanName             *string          `json:"plan_name"`
}

func (q *Queries) ListSubscriptionsForSuper(ctx context.Context, arg ListSubscriptionsForSuperParams) ([]ListSubscriptionsForSuperRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsForSuper,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubscriptionsForSuperRow
	for rows.Next() {
		var i ListSubscriptionsForSuperRow
		if err := rows.Scan(
			&i.Status,
			&i.StripeSubscriptionID,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.UserName,
			&i.RestaurantName,
			&i.PlanName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const platformTotals = `-- name: PlatformTotals :one
SELECT
  (SELECT COUNT(*) FROM restaurants)::bigint AS total_restaurants,
  (SELECT COUNT(*) FROM user_sessions)::bigint AS total_sessions,
  (SELECT COUNT(*) FROM ai_usage_logs)::bigint AS total_credits_used,
  (SELECT COUNT(*) FROM restaurants WHERE created_at >= date_trunc('month', now()))::bigint AS restaurants_this_month,
  (SELECT COUNT(*) FROM user_sessions WHERE created_at >= date_trunc('month', now()))::bigint AS sessions_this_month,
  (SELECT COUNT(*) FROM ai_usage_logs WHERE created_at >= date_trunc('month', now()))::bigint AS credits_this_month
`

type PlatformTotalsRow struct {
	TotalRestaurants     int64 `json:"total_restaurants"`
	TotalSessions        int64 `json:"total_sessions"`
	TotalCreditsUsed     int64 `json:"total_credits_used"`
	RestaurantsThisMonth int64 `json:"restaurants_this_month"`
	SessionsThisMonth    int64 `json:"sessions_this_month"`
	CreditsThisMonth     int64 `json:"credits_this_month"`
}

func (q *Queries) PlatformTotals(ctx context.Context) (PlatformTotalsRow, error) {
	row := q.db.QueryRow(ctx, platformTotals)
	var i PlatformTotalsRow
	err := row.Scan(
		&i.TotalRestaurants,
		&i.TotalSessions,
		&i.TotalCreditsUsed,
		&i.RestaurantsThisMonth,
		&i.SessionsThisMonth,
		&i.CreditsThisMonth,
	)
	return i, err
}

const setRestaurantSlug = `-- name: SetRestaurantSlug :exec
UPDATE restaurants SET slug = $1 WHERE id = $2
`

type SetRestaurantSlugParams struct {
	Slug *string     `json:"slug"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) SetRestaurantSlug(ctx context.Context, arg SetRestaurantSlugParams) error {
	_, err := q.db.Exec(ctx, setRestaurantSlug, arg.Slug, arg.ID)
	return err
}

const setRestaurantStatus = `-- name: SetRestaurantStatus :exec
UPDATE restaurants SET status = $1 WHERE id = $2
`

type SetRestaurantStatusParams struct {
	Status *RetaurantSetupStatus `json:"status"`
	ID     pgtype.UUID           `json:"id"`
}

func (q *Queries) SetRestaurantStatus(ctx context.Context, arg SetRestaurantStatusParams) error {
	_, err := q.db.Exec(ctx, setRestaurantStatus, arg.Status, arg.ID)
	return err
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE account SET password = $1, updated_at = now()
WHERE user_id = $2 AND provider_id = 'credential'
`

type SetUserPasswordParams struct {
	Password *string     `json:"password"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.Password, arg.UserID)
	return err
}

const subscriptionStatsChart = `-- name: SubscriptionStatsChart :many
SELECT COUNT(us.id)::bigint AS count,
       DATE_TRUNC('month', us.created_at)::timestamp AS month,
       sp.name AS plan_name
FROM user_subscriptions us
INNER JOIN subscriptions_plans sp ON us.plan_id = sp.id
GROUP BY sp.name, DATE_TRUNC('month', us.created_at)
ORDER BY month, sp.name
`

type SubscriptionStatsChartRow struct {
	Count    int64            `json:"count"`
	Month    pgtype.Timestamp `json:"month"`
	PlanName string           `json:"plan_name"`
}

func (q *Queries) SubscriptionStatsChart(ctx context.Context) ([]SubscriptionStatsChartRow, error) {
	rows, err := q.db.Query(ctx, subscriptionStatsChart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubscriptionStatsChartRow
	for rows.Next() {
		var i SubscriptionStatsChartRow
		if err := rows.Scan(&i.Count, &i.Month, &i.PlanName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleRestaurantSuspended = `-- name: ToggleRestaurantSuspended :exec
UPDATE restaurants
SET suspended = $1, suspended_reason = $2, suspended_at = $3, suspended_by = $4
WHERE id = $5
`

type ToggleRestaurantSuspendedParams struct {
	Suspended       bool             `json:"suspended"`
	SuspendedReason *string          `json:"suspended_reason"`
	SuspendedAt     pgtype.Timestamp `json:"suspended_at"`
	SuspendedBy     pgtype.UUID      `json:"suspended_by"`
	ID              pgtype.UUID      `json:"id"`
}

func (q *Queries) ToggleRestaurantSuspended(ctx context.Context, arg ToggleRestaurantSuspendedParams) error {
	_, err := q.db.Exec(ctx, toggleRestaurantSuspended,
		arg.Suspended,
		arg.SuspendedReason,
		arg.SuspendedAt,
		arg.SuspendedBy,
		arg.ID,
	)
	return err
}

const updateAllergen = `-- name: UpdateAllergen :exec
UPDATE allergens SET name = $1 WHERE id = $2
`

type UpdateAllergenParams struct {
	Name string      `json:"name"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateAllergen(ctx context.Context, arg UpdateAllergenParams) error {
	_, err := q.db.Exec(ctx, updateAllergen, arg.Name, arg.ID)
	return err
}

const updateSubscriptionCancelAtPeriodEnd = `-- name: UpdateSubscriptionCancelAtPeriodEnd :exec
UPDATE user_subscriptions SET cancel_at_period_end = $1, status = $2, updated_at = now()
WHERE stripe_subscription_id = $3
`

type UpdateSubscriptionCancelAtPeriodEndParams struct {
	CancelAtPeriodEnd    *bool   `json:"cancel_at_period_end"`
	Status               *string `json:"status"`
	StripeSubscriptionID string  `json:"stripe_subscription_id"`
}

func (q *Queries) UpdateSubscriptionCancelAtPeriodEnd(ctx context.Context, arg UpdateSubscriptionCancelAtPeriodEndParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionCancelAtPeriodEnd, arg.CancelAtPeriodEnd, arg.Status, arg.StripeSubscriptionID)
	return err
}

const updateSubscriptionFromWebhook = `-- name: UpdateSubscriptionFromWebhook :exec
UPDATE user_subscriptions SET
  status = $1, price_id = $2, updated_at = now(),
  current_period_start = $3, current_period_end = $4
WHERE id = $5
`

type UpdateSubscriptionFromWebhookParams struct {
	Status             *string          `json:"status"`
	PriceID            *string          `json:"price_id"`
	CurrentPeriodStart pgtype.Timestamp `json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamp `json:"current_period_end"`
	ID                 pgtype.UUID      `json:"id"`
}

func (q *Queries) UpdateSubscriptionFromWebhook(ctx context.Context, arg UpdateSubscriptionFromWebhookParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionFromWebhook,
		arg.Status,
		arg.PriceID,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.ID,
	)
	return err
}

const updateSubscriptionFull = `-- name: UpdateSubscriptionFull :exec
UPDATE user_subscriptions SET
  status = $1, current_period_start = $2, current_period_end = $3,
  canceled_at = $4, price_id = $5, stripe_subscription_id = $6, updated_at = now()
WHERE stripe_subscription_id = $7
`

type UpdateSubscriptionFullParams struct {
	Status                 *string          `json:"status"`
	CurrentPeriodStart     pgtype.Timestamp `json:"current_period_start"`
	CurrentPeriodEnd       pgtype.Timestamp `json:"current_period_end"`
	CanceledAt             pgtype.Timestamp `json:"canceled_at"`
	PriceID                *string          `json:"price_id"`
	StripeSubscriptionID   string           `json:"stripe_subscription_id"`
	StripeSubscriptionID_2 string           `json:"stripe_subscription_id_2"`
}

func (q *Queries) UpdateSubscriptionFull(ctx context.Context, arg UpdateSubscriptionFullParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionFull,
		arg.Status,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.CanceledAt,
		arg.PriceID,
		arg.StripeSubscriptionID,
		arg.StripeSubscriptionID_2,
	)
	return err
}

const updateSubscriptionPlanPrice = `-- name: UpdateSubscriptionPlanPrice :exec
UPDATE subscriptions_plans SET price_id = $1 WHERE product_id = $2
`

type UpdateSubscriptionPlanPriceParams struct {
	PriceID   *string `json:"price_id"`
	ProductID string  `json:"product_id"`
}

func (q *Queries) UpdateSubscriptionPlanPrice(ctx context.Context, arg UpdateSubscriptionPlanPriceParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionPlanPrice, arg.PriceID, arg.ProductID)
	return err
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :exec
UPDATE user_subscriptions SET status = $1, updated_at = now() WHERE id = $2
`

type UpdateSubscriptionStatusParams struct {
	Status *string     `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionStatus, arg.Status, arg.ID)
	return err
}

const upsertSubscription = `-- name: UpsertSubscription :exec
INSERT INTO user_subscriptions (id, user_id, stripe_subscription_id, stripe_customer_id, price_id, status, plan_id, created_at, updated_at)
VALUES (gen_random_uuid(), $1, $2, $3, $4, $5, $6, now(), now())
ON CONFLICT (user_id) DO UPDATE
  SET stripe_subscription_id = EXCLUDED.stripe_subscription_id,
      stripe_customer_id     = EXCLUDED.stripe_customer_id,
      price_id               = EXCLUDED.price_id,
      status                 = EXCLUDED.status,
      plan_id                = EXCLUDED.plan_id,
      updated_at             = now()
`

type UpsertSubscriptionParams struct {
	UserID               pgtype.UUID `json:"user_id"`
	StripeSubscriptionID string      `json:"stripe_subscription_id"`
	StripeCustomerID     string      `json:"stripe_customer_id"`
	PriceID              *string     `json:"price_id"`
	Status               *string     `json:"status"`
	PlanID               pgtype.UUID `json:"plan_id"`
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) error {
	_, err := q.db.Exec(ctx, upsertSubscription,
		arg.UserID,
		arg.StripeSubscriptionID,
		arg.StripeCustomerID,
		arg.PriceID,
		arg.Status,
		arg.PlanID,
	)
	return err
}

const upsertSubscriptionPlan = `-- name: UpsertSubscriptionPlan :exec
INSERT INTO subscriptions_plans (id, product_id, name, price_id, created_at)
VALUES (gen_random_uuid(), $1, $2, $3, now())
ON CONFLICT (name) DO UPDATE
  SET price_id   = COALESCE(EXCLUDED.price_id, subscriptions_plans.price_id),
      product_id = EXCLUDED.product_id
`

type UpsertSubscriptionPlanParams struct {
	ProductID string  `json:"product_id"`
	Name      string  `json:"name"`
	PriceID   *string `json:"price_id"`
}

func (q *Queries) UpsertSubscriptionPlan(ctx context.Context, arg UpsertSubscriptionPlanParams) error {
	_, err := q.db.Exec(ctx, upsertSubscriptionPlan, arg.ProductID, arg.Name, arg.PriceID)
	return err
}
