// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_data.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReview = `-- name: CreateReview :exec
INSERT INTO reviews (id, reviewable_id, rating, comment, restaurant_id, created_at)
VALUES (gen_random_uuid(), $1, $2, $3, $4, now())
`

type CreateReviewParams struct {
	ReviewableID pgtype.UUID `json:"reviewable_id"`
	Rating       int32       `json:"rating"`
	Comment      string      `json:"comment"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) error {
	_, err := q.db.Exec(ctx, createReview,
		arg.ReviewableID,
		arg.Rating,
		arg.Comment,
		arg.RestaurantID,
	)
	return err
}

const deleteSessionAllergens = `-- name: DeleteSessionAllergens :exec
DELETE FROM user_session_allergens WHERE session_id = $1
`

func (q *Queries) DeleteSessionAllergens(ctx context.Context, sessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionAllergens, sessionID)
	return err
}

const deleteSessionTags = `-- name: DeleteSessionTags :exec
DELETE FROM user_session_tags WHERE session_id = $1
`

func (q *Queries) DeleteSessionTags(ctx context.Context, sessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionTags, sessionID)
	return err
}

const getAISessionInfo = `-- name: GetAISessionInfo :one
SELECT r.id, us.stripe_customer_id, us.stripe_subscription_id
FROM restaurants r
LEFT JOIN users u ON u.restaurant_id = r.id
LEFT JOIN user_subscriptions us ON us.user_id = u.id
WHERE r.id = $1
LIMIT 1
`

type GetAISessionInfoRow struct {
	ID                   pgtype.UUID `json:"id"`
	StripeCustomerID     *string     `json:"stripe_customer_id"`
	StripeSubscriptionID *string     `json:"stripe_subscription_id"`
}

func (q *Queries) GetAISessionInfo(ctx context.Context, id pgtype.UUID) (GetAISessionInfoRow, error) {
	row := q.db.QueryRow(ctx, getAISessionInfo, id)
	var i GetAISessionInfoRow
	err := row.Scan(&i.ID, &i.StripeCustomerID, &i.StripeSubscriptionID)
	return i, err
}

const getRestaurantForDiner = `-- name: GetRestaurantForDiner :one
SELECT id, name, description, image, banner_url, address, phone, website, slug FROM restaurants WHERE id = $1
`

type GetRestaurantForDinerRow struct {
	ID          pgtype.UUID `json:"id"`
	Name        *string     `json:"name"`
	Description *string     `json:"description"`
	Image       *string     `json:"image"`
	BannerUrl   *string     `json:"banner_url"`
	Address     *string     `json:"address"`
	Phone       *string     `json:"phone"`
	Website     *string     `json:"website"`
	Slug        *string     `json:"slug"`
}

func (q *Queries) GetRestaurantForDiner(ctx context.Context, id pgtype.UUID) (GetRestaurantForDinerRow, error) {
	row := q.db.QueryRow(ctx, getRestaurantForDiner, id)
	var i GetRestaurantForDinerRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Image,
		&i.BannerUrl,
		&i.Address,
		&i.Phone,
		&i.Website,
		&i.Slug,
	)
	return i, err
}

const getReviewsForItem = `-- name: GetReviewsForItem :many
SELECT id, rating, comment, created_at
FROM reviews
WHERE reviewable_id = $1
ORDER BY created_at DESC
LIMIT 20
`

type GetReviewsForItemRow struct {
	ID        pgtype.UUID      `json:"id"`
	Rating    int32            `json:"rating"`
	Comment   string           `json:"comment"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetReviewsForItem(ctx context.Context, reviewableID pgtype.UUID) ([]GetReviewsForItemRow, error) {
	rows, err := q.db.Query(ctx, getReviewsForItem, reviewableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReviewsForItemRow
	for rows.Next() {
		var i GetReviewsForItemRow
		if err := rows.Scan(
			&i.ID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionPreferenceAllergens = `-- name: GetSessionPreferenceAllergens :many
SELECT allergen_id FROM user_session_allergens WHERE session_id = $1
`

func (q *Queries) GetSessionPreferenceAllergens(ctx context.Context, sessionID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getSessionPreferenceAllergens, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var allergen_id pgtype.UUID
		if err := rows.Scan(&allergen_id); err != nil {
			return nil, err
		}
		items = append(items, allergen_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSessionPreferenceTags = `-- name: GetSessionPreferenceTags :many
SELECT tag_id FROM user_session_tags WHERE session_id = $1
`

func (q *Queries) GetSessionPreferenceTags(ctx context.Context, sessionID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getSessionPreferenceTags, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var tag_id pgtype.UUID
		if err := rows.Scan(&tag_id); err != nil {
			return nil, err
		}
		items = append(items, tag_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSessionAllergen = `-- name: InsertSessionAllergen :exec
INSERT INTO user_session_allergens (session_id, allergen_id) VALUES ($1, $2)
`

type InsertSessionAllergenParams struct {
	SessionID  pgtype.UUID `json:"session_id"`
	AllergenID pgtype.UUID `json:"allergen_id"`
}

func (q *Queries) InsertSessionAllergen(ctx context.Context, arg InsertSessionAllergenParams) error {
	_, err := q.db.Exec(ctx, insertSessionAllergen, arg.SessionID, arg.AllergenID)
	return err
}

const insertSessionTag = `-- name: InsertSessionTag :exec
INSERT INTO user_session_tags (session_id, tag_id) VALUES ($1, $2)
`

type InsertSessionTagParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	TagID     pgtype.UUID `json:"tag_id"`
}

func (q *Queries) InsertSessionTag(ctx context.Context, arg InsertSessionTagParams) error {
	_, err := q.db.Exec(ctx, insertSessionTag, arg.SessionID, arg.TagID)
	return err
}

const listAllergens = `-- name: ListAllergens :many
SELECT id, name, translations FROM allergens ORDER BY name
`

type ListAllergensRow struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Translations []byte      `json:"translations"`
}

func (q *Queries) ListAllergens(ctx context.Context) ([]ListAllergensRow, error) {
	rows, err := q.db.Query(ctx, listAllergens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllergensRow
	for rows.Next() {
		var i ListAllergensRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Translations); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDietTagsByRestaurant = `-- name: ListDietTagsByRestaurant :many
SELECT id, name, description, translations
FROM tags
WHERE type = 'diet' AND (restaurant_id = $1 OR is_system = true)
ORDER BY name
`

type ListDietTagsByRestaurantRow struct {
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Description  *string     `json:"description"`
	Translations []byte      `json:"translations"`
}

func (q *Queries) ListDietTagsByRestaurant(ctx context.Context, restaurantID pgtype.UUID) ([]ListDietTagsByRestaurantRow, error) {
	rows, err := q.db.Query(ctx, listDietTagsByRestaurant, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDietTagsByRestaurantRow
	for rows.Next() {
		var i ListDietTagsByRestaurantRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Translations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByRestaurant = `-- name: ListTagsByRestaurant :many
SELECT id, name, type FROM tags WHERE restaurant_id = $1 ORDER BY name
`

type ListTagsByRestaurantRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
	Type TagType     `json:"type"`
}

func (q *Queries) ListTagsByRestaurant(ctx context.Context, restaurantID pgtype.UUID) ([]ListTagsByRestaurantRow, error) {
	rows, err := q.db.Query(ctx, listTagsByRestaurant, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsByRestaurantRow
	for rows.Next() {
		var i ListTagsByRestaurantRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByRestaurantAndType = `-- name: ListTagsByRestaurantAndType :many
SELECT id, name, type FROM tags WHERE restaurant_id = $1 AND type = $2 ORDER BY name
`

type ListTagsByRestaurantAndTypeParams struct {
	RestaurantID pgtype.UUID `json:"restaurant_id"`
	Type         TagType     `json:"type"`
}

type ListTagsByRestaurantAndTypeRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
	Type TagType     `json:"type"`
}

func (q *Queries) ListTagsByRestaurantAndType(ctx context.Context, arg ListTagsByRestaurantAndTypeParams) ([]ListTagsByRestaurantAndTypeRow, error) {
	rows, err := q.db.Query(ctx, listTagsByRestaurantAndType, arg.RestaurantID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsByRestaurantAndTypeRow
	for rows.Next() {
		var i ListTagsByRestaurantAndTypeRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const menuItemBelongsToRestaurant = `-- name: MenuItemBelongsToRestaurant :one
SELECT id FROM menu_items WHERE id = $1 AND restaurant_id = $2
`

type MenuItemBelongsToRestaurantParams struct {
	ID           pgtype.UUID `json:"id"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
}

func (q *Queries) MenuItemBelongsToRestaurant(ctx context.Context, arg MenuItemBelongsToRestaurantParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, menuItemBelongsToRestaurant, arg.ID, arg.RestaurantID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
