// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_menu.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMenuItemDetailByID = `-- name: GetMenuItemDetailByID :one
SELECT id, section_id, name, description, translations, ingredients, images, price,
       discount_type, discount_value, discount_start_at, discount_end_at, discount_label,
       is_available, spice_level, cook_time, is_alcoholic, has_variants,
       is_chefs_recommended, is_popular, is_new, is_limited_time, created_at, type
FROM menu_items
WHERE id = $1 AND restaurant_id = $2
`

type GetMenuItemDetailByIDParams struct {
	ID           pgtype.UUID `json:"id"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
}

type GetMenuItemDetailByIDRow struct {
	ID                 pgtype.UUID      `json:"id"`
	SectionID          pgtype.UUID      `json:"section_id"`
	Name               string           `json:"name"`
	Description        *string          `json:"description"`
	Translations       []byte           `json:"translations"`
	Ingredients        []string         `json:"ingredients"`
	Images             []string         `json:"images"`
	Price              pgtype.Numeric   `json:"price"`
	DiscountType       *string          `json:"discount_type"`
	DiscountValue      pgtype.Numeric   `json:"discount_value"`
	DiscountStartAt    pgtype.Timestamp `json:"discount_start_at"`
	DiscountEndAt      pgtype.Timestamp `json:"discount_end_at"`
	DiscountLabel      *string          `json:"discount_label"`
	IsAvailable        *bool            `json:"is_available"`
	SpiceLevel         *SpiceLevel      `json:"spice_level"`
	CookTime           *int32           `json:"cook_time"`
	IsAlcoholic        *bool            `json:"is_alcoholic"`
	HasVariants        *bool            `json:"has_variants"`
	IsChefsRecommended *bool            `json:"is_chefs_recommended"`
	IsPopular          *bool            `json:"is_popular"`
	IsNew              *bool            `json:"is_new"`
	IsLimitedTime      *bool            `json:"is_limited_time"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	Type               string           `json:"type"`
}

func (q *Queries) GetMenuItemDetailByID(ctx context.Context, arg GetMenuItemDetailByIDParams) (GetMenuItemDetailByIDRow, error) {
	row := q.db.QueryRow(ctx, getMenuItemDetailByID, arg.ID, arg.RestaurantID)
	var i GetMenuItemDetailByIDRow
	err := row.Scan(
		&i.ID,
		&i.SectionID,
		&i.Name,
		&i.Description,
		&i.Translations,
		&i.Ingredients,
		&i.Images,
		&i.Price,
		&i.DiscountType,
		&i.DiscountValue,
		&i.DiscountStartAt,
		&i.DiscountEndAt,
		&i.DiscountLabel,
		&i.IsAvailable,
		&i.SpiceLevel,
		&i.CookTime,
		&i.IsAlcoholic,
		&i.HasVariants,
		&i.IsChefsRecommended,
		&i.IsPopular,
		&i.IsNew,
		&i.IsLimitedTime,
		&i.CreatedAt,
		&i.Type,
	)
	return i, err
}

const getMenuItemForAI = `-- name: GetMenuItemForAI :one
SELECT mi.id, mi.name, mi.description, mi.price, mi.images, mi.type, mi.translations
FROM menu_items mi
WHERE mi.id = $1 AND mi.restaurant_id = $2
`

type GetMenuItemForAIParams struct {
	ID           pgtype.UUID `json:"id"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
}

type GetMenuItemForAIRow struct {
	ID           pgtype.UUID    `json:"id"`
	Name         string         `json:"name"`
	Description  *string        `json:"description"`
	Price        pgtype.Numeric `json:"price"`
	Images       []string       `json:"images"`
	Type         string         `json:"type"`
	Translations []byte         `json:"translations"`
}

func (q *Queries) GetMenuItemForAI(ctx context.Context, arg GetMenuItemForAIParams) (GetMenuItemForAIRow, error) {
	row := q.db.QueryRow(ctx, getMenuItemForAI, arg.ID, arg.RestaurantID)
	var i GetMenuItemForAIRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Images,
		&i.Type,
		&i.Translations,
	)
	return i, err
}

const listAllMenuItemsForRestaurant = `-- name: ListAllMenuItemsForRestaurant :many
SELECT mi.id, mi.name, mi.description, mi.translations, mi.images, mi.price, mi.type,
       mi.section_id, mi.is_available, mi.created_at,
       ms.id AS ms_id, ms.name AS ms_name, ms.sort_order AS ms_sort_order,
       ms.translations AS ms_translations
FROM menu_items mi
LEFT JOIN menu_sections ms ON mi.section_id = ms.id
WHERE mi.restaurant_id = $1
`

type ListAllMenuItemsForRestaurantRow struct {
	ID             pgtype.UUID      `json:"id"`
	Name           string           `json:"name"`
	Description    *string          `json:"description"`
	Translations   []byte           `json:"translations"`
	Images         []string         `json:"images"`
	Price          pgtype.Numeric   `json:"price"`
	Type           string           `json:"type"`
	SectionID      pgtype.UUID      `json:"section_id"`
	IsAvailable    *bool            `json:"is_available"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	MsID           pgtype.UUID      `json:"ms_id"`
	MsName         *string          `json:"ms_name"`
	MsSortOrder    *int32           `json:"ms_sort_order"`
	MsTranslations []byte           `json:"ms_translations"`
}

func (q *Queries) ListAllMenuItemsForRestaurant(ctx context.Context, restaurantID pgtype.UUID) ([]ListAllMenuItemsForRestaurantRow, error) {
	rows, err := q.db.Query(ctx, listAllMenuItemsForRestaurant, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllMenuItemsForRestaurantRow
	for rows.Next() {
		var i ListAllMenuItemsForRestaurantRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Translations,
			&i.Images,
			&i.Price,
			&i.Type,
			&i.SectionID,
			&i.IsAvailable,
			&i.CreatedAt,
			&i.MsID,
			&i.MsName,
			&i.MsSortOrder,
			&i.MsTranslations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassifiedMenuItems = `-- name: ListClassifiedMenuItems :many
SELECT mi.id, mi.name, mi.description, mi.translations, mi.images, mi.price, mi.type, mi.has_variants,
       mi.is_chefs_recommended, mi.is_popular, mi.is_new, mi.is_limited_time, mi.is_available, mi.created_at
FROM menu_items mi
JOIN menu_sections ms ON mi.section_id = ms.id
WHERE ms.menu_id = $1 AND mi.restaurant_id = $2
  AND (mi.is_chefs_recommended = true OR mi.is_popular = true OR mi.is_new = true OR mi.is_limited_time = true)
`

type ListClassifiedMenuItemsParams struct {
	MenuID       pgtype.UUID `json:"menu_id"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
}

type ListClassifiedMenuItemsRow struct {
	ID                 pgtype.UUID      `json:"id"`
	Name               string           `json:"name"`
	Description        *string          `json:"description"`
	Translations       []byte           `json:"translations"`
	Images             []string         `json:"images"`
	Price              pgtype.Numeric   `json:"price"`
	Type               string           `json:"type"`
	HasVariants        *bool            `json:"has_variants"`
	IsChefsRecommended *bool            `json:"is_chefs_recommended"`
	IsPopular          *bool            `json:"is_popular"`
	IsNew              *bool            `json:"is_new"`
	IsLimitedTime      *bool            `json:"is_limited_time"`
	IsAvailable        *bool            `json:"is_available"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) ListClassifiedMenuItems(ctx context.Context, arg ListClassifiedMenuItemsParams) ([]ListClassifiedMenuItemsRow, error) {
	rows, err := q.db.Query(ctx, listClassifiedMenuItems, arg.MenuID, arg.RestaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClassifiedMenuItemsRow
	for rows.Next() {
		var i ListClassifiedMenuItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Translations,
			&i.Images,
			&i.Price,
			&i.Type,
			&i.HasVariants,
			&i.IsChefsRecommended,
			&i.IsPopular,
			&i.IsNew,
			&i.IsLimitedTime,
			&i.IsAvailable,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemAddonsByItemID = `-- name: ListItemAddonsByItemID :many
SELECT a.id, a.name, a.price, a.translations
FROM menu_item_addons mia
JOIN addons a ON mia.addon_id = a.id
WHERE mia.item_id = $1
`

type ListItemAddonsByItemIDRow struct {
	ID           pgtype.UUID    `json:"id"`
	Name         string         `json:"name"`
	Price        pgtype.Numeric `json:"price"`
	Translations []byte         `json:"translations"`
}

func (q *Queries) ListItemAddonsByItemID(ctx context.Context, itemID pgtype.UUID) ([]ListItemAddonsByItemIDRow, error) {
	rows, err := q.db.Query(ctx, listItemAddonsByItemID, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemAddonsByItemIDRow
	for rows.Next() {
		var i ListItemAddonsByItemIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Translations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemAllergensByItemIDs = `-- name: ListItemAllergensByItemIDs :many
SELECT mia.menu_item_id, a.id, a.name, a.translations
FROM menu_item_allergens mia
JOIN allergens a ON mia.allergen_id = a.id
WHERE mia.menu_item_id = ANY($1::uuid[])
`

type ListItemAllergensByItemIDsRow struct {
	MenuItemID   pgtype.UUID `json:"menu_item_id"`
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Translations []byte      `json:"translations"`
}

func (q *Queries) ListItemAllergensByItemIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListItemAllergensByItemIDsRow, error) {
	rows, err := q.db.Query(ctx, listItemAllergensByItemIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemAllergensByItemIDsRow
	for rows.Next() {
		var i ListItemAllergensByItemIDsRow
		if err := rows.Scan(
			&i.MenuItemID,
			&i.ID,
			&i.Name,
			&i.Translations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemTagsByItemIDs = `-- name: ListItemTagsByItemIDs :many
SELECT mit.menu_item_id, t.id, t.name, t.description, t.translations, t.type
FROM menu_item_tags mit
JOIN tags t ON mit.tag_id = t.id
WHERE mit.menu_item_id = ANY($1::uuid[])
`

type ListItemTagsByItemIDsRow struct {
	MenuItemID   pgtype.UUID `json:"menu_item_id"`
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	Description  *string     `json:"description"`
	Translations []byte      `json:"translations"`
	Type         TagType     `json:"type"`
}

func (q *Queries) ListItemTagsByItemIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListItemTagsByItemIDsRow, error) {
	rows, err := q.db.Query(ctx, listItemTagsByItemIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemTagsByItemIDsRow
	for rows.Next() {
		var i ListItemTagsByItemIDsRow
		if err := rows.Scan(
			&i.MenuItemID,
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Translations,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemTagsForAI = `-- name: ListItemTagsForAI :many
SELECT mit.menu_item_id, t.name, t.type
FROM menu_item_tags mit
JOIN tags t ON mit.tag_id = t.id
WHERE mit.menu_item_id = ANY($1::uuid[])
`

type ListItemTagsForAIRow struct {
	MenuItemID pgtype.UUID `json:"menu_item_id"`
	Name       string      `json:"name"`
	Type       TagType     `json:"type"`
}

func (q *Queries) ListItemTagsForAI(ctx context.Context, dollar_1 []pgtype.UUID) ([]ListItemTagsForAIRow, error) {
	rows, err := q.db.Query(ctx, listItemTagsForAI, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemTagsForAIRow
	for rows.Next() {
		var i ListItemTagsForAIRow
		if err := rows.Scan(&i.MenuItemID, &i.Name, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemVariantsByItemID = `-- name: ListItemVariantsByItemID :many
SELECT id, name, price, is_available, translations, image
FROM menu_item_variants
WHERE item_id = $1
`

type ListItemVariantsByItemIDRow struct {
	ID           pgtype.UUID    `json:"id"`
	Name         string         `json:"name"`
	Price        pgtype.Numeric `json:"price"`
	IsAvailable  *bool          `json:"is_available"`
	Translations []byte         `json:"translations"`
	Image        *string        `json:"image"`
}

func (q *Queries) ListItemVariantsByItemID(ctx context.Context, itemID pgtype.UUID) ([]ListItemVariantsByItemIDRow, error) {
	rows, err := q.db.Query(ctx, listItemVariantsByItemID, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemVariantsByItemIDRow
	for rows.Next() {
		var i ListItemVariantsByItemIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.IsAvailable,
			&i.Translations,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuItemImagesForMenu = `-- name: ListMenuItemImagesForMenu :many
SELECT ms.menu_id, mi.images
FROM menu_sections ms
JOIN menu_items mi ON mi.section_id = ms.id
WHERE ms.menu_id = $1 AND array_length(mi.images, 1) > 0
ORDER BY mi.created_at
`

type ListMenuItemImagesForMenuRow struct {
	MenuID pgtype.UUID `json:"menu_id"`
	Images []string    `json:"images"`
}

func (q *Queries) ListMenuItemImagesForMenu(ctx context.Context, menuID pgtype.UUID) ([]ListMenuItemImagesForMenuRow, error) {
	rows, err := q.db.Query(ctx, listMenuItemImagesForMenu, menuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMenuItemImagesForMenuRow
	for rows.Next() {
		var i ListMenuItemImagesForMenuRow
		if err := rows.Scan(&i.MenuID, &i.Images); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuItemsByMenu = `-- name: ListMenuItemsByMenu :many
SELECT mi.id, mi.section_id, mi.name, mi.description, mi.translations, mi.images, mi.price,
       mi.discount_type, mi.discount_value, mi.discount_start_at, mi.discount_end_at,
       mi.discount_label, mi.is_available, mi.spice_level, mi.cook_time, mi.is_alcoholic,
       mi.has_variants, mi.is_chefs_recommended, mi.is_popular, mi.is_new, mi.is_limited_time,
       mi.created_at, mi.type
FROM menu_items mi
JOIN menu_sections ms ON mi.section_id = ms.id
WHERE ms.menu_id = $1 AND mi.restaurant_id = $2
ORDER BY mi.created_at DESC
`

type ListMenuItemsByMenuParams struct {
	MenuID       pgtype.UUID `json:"menu_id"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
}

type ListMenuItemsByMenuRow struct {
	ID                 pgtype.UUID      `json:"id"`
	SectionID          pgtype.UUID      `json:"section_id"`
	Name               string           `json:"name"`
	Description        *string          `json:"description"`
	Translations       []byte           `json:"translations"`
	Images             []string         `json:"images"`
	Price              pgtype.Numeric   `json:"price"`
	DiscountType       *string          `json:"discount_type"`
	DiscountValue      pgtype.Numeric   `json:"discount_value"`
	DiscountStartAt    pgtype.Timestamp `json:"discount_start_at"`
	DiscountEndAt      pgtype.Timestamp `json:"discount_end_at"`
	DiscountLabel      *string          `json:"discount_label"`
	IsAvailable        *bool            `json:"is_available"`
	SpiceLevel         *SpiceLevel      `json:"spice_level"`
	CookTime           *int32           `json:"cook_time"`
	IsAlcoholic        *bool            `json:"is_alcoholic"`
	HasVariants        *bool            `json:"has_variants"`
	IsChefsRecommended *bool            `json:"is_chefs_recommended"`
	IsPopular          *bool            `json:"is_popular"`
	IsNew              *bool            `json:"is_new"`
	IsLimitedTime      *bool            `json:"is_limited_time"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	Type               string           `json:"type"`
}

func (q *Queries) ListMenuItemsByMenu(ctx context.Context, arg ListMenuItemsByMenuParams) ([]ListMenuItemsByMenuRow, error) {
	rows, err := q.db.Query(ctx, listMenuItemsByMenu, arg.MenuID, arg.RestaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMenuItemsByMenuRow
	for rows.Next() {
		var i ListMenuItemsByMenuRow
		if err := rows.Scan(
			&i.ID,
			&i.SectionID,
			&i.Name,
			&i.Description,
			&i.Translations,
			&i.Images,
			&i.Price,
			&i.DiscountType,
			&i.DiscountValue,
			&i.DiscountStartAt,
			&i.DiscountEndAt,
			&i.DiscountLabel,
			&i.IsAvailable,
			&i.SpiceLevel,
			&i.CookTime,
			&i.IsAlcoholic,
			&i.HasVariants,
			&i.IsChefsRecommended,
			&i.IsPopular,
			&i.IsNew,
			&i.IsLimitedTime,
			&i.CreatedAt,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuItemsForAI = `-- name: ListMenuItemsForAI :many
SELECT mi.id, mi.name, mi.description, mi.price, mi.images, mi.type
FROM menu_items mi
WHERE mi.restaurant_id = $1
`

type ListMenuItemsForAIRow struct {
	ID          pgtype.UUID    `json:"id"`
	Name        string         `json:"name"`
	Description *string        `json:"description"`
	Price       pgtype.Numeric `json:"price"`
	Images      []string       `json:"images"`
	Type        string         `json:"type"`
}

func (q *Queries) ListMenuItemsForAI(ctx context.Context, restaurantID pgtype.UUID) ([]ListMenuItemsForAIRow, error) {
	rows, err := q.db.Query(ctx, listMenuItemsForAI, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMenuItemsForAIRow
	for rows.Next() {
		var i ListMenuItemsForAIRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Images,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuSectionsByMenuID = `-- name: ListMenuSectionsByMenuID :many
SELECT ms.id, ms.name, ms.description, ms.translations, ms.sort_order, ms.created_at,
       m.name AS menu_name, m.translations AS menu_translations, m.description AS menu_description
FROM menu_sections ms
JOIN menu m ON ms.menu_id = m.id
WHERE ms.menu_id = $1 AND m.restaurant_id = $2
ORDER BY ms.sort_order ASC
`

type ListMenuSectionsByMenuIDParams struct {
	MenuID       pgtype.UUID `json:"menu_id"`
	RestaurantID pgtype.UUID `json:"restaurant_id"`
}

type ListMenuSectionsByMenuIDRow struct {
	ID               pgtype.UUID      `json:"id"`
	Name             string           `json:"name"`
	Description      *string          `json:"description"`
	Translations     []byte           `json:"translations"`
	SortOrder        *int32           `json:"sort_order"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	MenuName         string           `json:"menu_name"`
	MenuTranslations []byte           `json:"menu_translations"`
	MenuDescription  *string          `json:"menu_description"`
}

func (q *Queries) ListMenuSectionsByMenuID(ctx context.Context, arg ListMenuSectionsByMenuIDParams) ([]ListMenuSectionsByMenuIDRow, error) {
	rows, err := q.db.Query(ctx, listMenuSectionsByMenuID, arg.MenuID, arg.RestaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMenuSectionsByMenuIDRow
	for rows.Next() {
		var i ListMenuSectionsByMenuIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Translations,
			&i.SortOrder,
			&i.CreatedAt,
			&i.MenuName,
			&i.MenuTranslations,
			&i.MenuDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenusByRestaurant = `-- name: ListMenusByRestaurant :many
SELECT id, name, description, translations, active, start_time, end_time, created_at, updated_at
FROM menu
WHERE restaurant_id = $1
`

type ListMenusByRestaurantRow struct {
	ID           pgtype.UUID      `json:"id"`
	Name         string           `json:"name"`
	Description  *string          `json:"description"`
	Translations []byte           `json:"translations"`
	Active       *bool            `json:"active"`
	StartTime    *string          `json:"start_time"`
	EndTime      *string          `json:"end_time"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListMenusByRestaurant(ctx context.Context, restaurantID pgtype.UUID) ([]ListMenusByRestaurantRow, error) {
	rows, err := q.db.Query(ctx, listMenusByRestaurant, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMenusByRestaurantRow
	for rows.Next() {
		var i ListMenusByRestaurantRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Translations,
			&i.Active,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
