# fly.toml app configuration file generated for saucy-menu-backend-ancient-cloud-8119 on 2025-04-06T19:35:13Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'saucy-menu-backend'
primary_region = 'ams'

[build]

[[services]]
[env]
  PORT = '8080'
  REDIS_URL = "redis://default:a69ad9b1dfc6440e856cb68dd14bc57c@fly-saucy-cache.upstash.io:6379"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  release_command = "bun run migrate"