export const apiRoutes = {
  verify: '/user/auth/session',
  setup: '/shared/base/setup',
  tags: '/user/preferences',
  userPreferences: '/user/preferences/',
  dishes: '/user/dishes',
  drinks: '/user/drinks',
  dishTags: '/user/dishes/tags',
  personalizedMenu: '/user/dishes/personalized-menu',
  menuSections: '/user/menu-sections',
  review: '/user/reviews',
  getRestaurant: '/user/auth/restaurant',
  menus: '/user/menu',
  classifiedItems: '/user/menu-items/classified-items',
  menuItems: '/user/menu-items',
  allergensClassifications: '/user/classifications/allergens',
  dietsClassifications: '/user/classifications/diets',
  menuItemsByMenuId: `/user/menu-items`,
}
