/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetupIndexRouteImport } from './routes/setup/index'
import { Route as SetupWelcomeRouteImport } from './routes/setup/welcome'
import { Route as SetupAllergenInfoRouteImport } from './routes/setup/allergenInfo'
import { Route as RSlugRouteImport } from './routes/r/$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as MainMenusIndexRouteImport } from './routes/main/menus/index'
import { Route as MainFoodIndexRouteImport } from './routes/main/food/index'
import { Route as MainMenusItemsRouteImport } from './routes/main/menus/items'
import { Route as MainMenusMenuIdRouteImport } from './routes/main/menus/$menuId'
import { Route as MainFoodItemIdRouteImport } from './routes/main/food/$itemId'
import { Route as MainChatItemIdRouteImport } from './routes/main/chat/$itemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/setup/',
  path: '/setup/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupWelcomeRoute = SetupWelcomeRouteImport.update({
  id: '/setup/welcome',
  path: '/setup/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupAllergenInfoRoute = SetupAllergenInfoRouteImport.update({
  id: '/setup/allergenInfo',
  path: '/setup/allergenInfo',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const MainMenusIndexRoute = MainMenusIndexRouteImport.update({
  id: '/main/menus/',
  path: '/main/menus/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainFoodIndexRoute = MainFoodIndexRouteImport.update({
  id: '/main/food/',
  path: '/main/food/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainMenusItemsRoute = MainMenusItemsRouteImport.update({
  id: '/main/menus/items',
  path: '/main/menus/items',
  getParentRoute: () => rootRouteImport,
} as any)
const MainMenusMenuIdRoute = MainMenusMenuIdRouteImport.update({
  id: '/main/menus/$menuId',
  path: '/main/menus/$menuId',
  getParentRoute: () => rootRouteImport,
} as any)
const MainFoodItemIdRoute = MainFoodItemIdRouteImport.update({
  id: '/main/food/$itemId',
  path: '/main/food/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const MainChatItemIdRoute = MainChatItemIdRouteImport.update({
  id: '/main/chat/$itemId',
  path: '/main/chat/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/r/$slug': typeof RSlugRoute
  '/setup/allergenInfo': typeof SetupAllergenInfoRoute
  '/setup/welcome': typeof SetupWelcomeRoute
  '/setup/': typeof SetupIndexRoute
  '/main/chat/$itemId': typeof MainChatItemIdRoute
  '/main/food/$itemId': typeof MainFoodItemIdRoute
  '/main/menus/$menuId': typeof MainMenusMenuIdRoute
  '/main/menus/items': typeof MainMenusItemsRoute
  '/main/food/': typeof MainFoodIndexRoute
  '/main/menus/': typeof MainMenusIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/r/$slug': typeof RSlugRoute
  '/setup/allergenInfo': typeof SetupAllergenInfoRoute
  '/setup/welcome': typeof SetupWelcomeRoute
  '/setup': typeof SetupIndexRoute
  '/main/chat/$itemId': typeof MainChatItemIdRoute
  '/main/food/$itemId': typeof MainFoodItemIdRoute
  '/main/menus/$menuId': typeof MainMenusMenuIdRoute
  '/main/menus/items': typeof MainMenusItemsRoute
  '/main/food': typeof MainFoodIndexRoute
  '/main/menus': typeof MainMenusIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/r/$slug': typeof RSlugRoute
  '/setup/allergenInfo': typeof SetupAllergenInfoRoute
  '/setup/welcome': typeof SetupWelcomeRoute
  '/setup/': typeof SetupIndexRoute
  '/main/chat/$itemId': typeof MainChatItemIdRoute
  '/main/food/$itemId': typeof MainFoodItemIdRoute
  '/main/menus/$menuId': typeof MainMenusMenuIdRoute
  '/main/menus/items': typeof MainMenusItemsRoute
  '/main/food/': typeof MainFoodIndexRoute
  '/main/menus/': typeof MainMenusIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/r/$slug'
    | '/setup/allergenInfo'
    | '/setup/welcome'
    | '/setup/'
    | '/main/chat/$itemId'
    | '/main/food/$itemId'
    | '/main/menus/$menuId'
    | '/main/menus/items'
    | '/main/food/'
    | '/main/menus/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/r/$slug'
    | '/setup/allergenInfo'
    | '/setup/welcome'
    | '/setup'
    | '/main/chat/$itemId'
    | '/main/food/$itemId'
    | '/main/menus/$menuId'
    | '/main/menus/items'
    | '/main/food'
    | '/main/menus'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/r/$slug'
    | '/setup/allergenInfo'
    | '/setup/welcome'
    | '/setup/'
    | '/main/chat/$itemId'
    | '/main/food/$itemId'
    | '/main/menus/$menuId'
    | '/main/menus/items'
    | '/main/food/'
    | '/main/menus/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  RSlugRoute: typeof RSlugRoute
  SetupAllergenInfoRoute: typeof SetupAllergenInfoRoute
  SetupWelcomeRoute: typeof SetupWelcomeRoute
  SetupIndexRoute: typeof SetupIndexRoute
  MainChatItemIdRoute: typeof MainChatItemIdRoute
  MainFoodItemIdRoute: typeof MainFoodItemIdRoute
  MainMenusMenuIdRoute: typeof MainMenusMenuIdRoute
  MainMenusItemsRoute: typeof MainMenusItemsRoute
  MainFoodIndexRoute: typeof MainFoodIndexRoute
  MainMenusIndexRoute: typeof MainMenusIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/setup'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/welcome': {
      id: '/setup/welcome'
      path: '/setup/welcome'
      fullPath: '/setup/welcome'
      preLoaderRoute: typeof SetupWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/allergenInfo': {
      id: '/setup/allergenInfo'
      path: '/setup/allergenInfo'
      fullPath: '/setup/allergenInfo'
      preLoaderRoute: typeof SetupAllergenInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main/menus/': {
      id: '/main/menus/'
      path: '/main/menus'
      fullPath: '/main/menus/'
      preLoaderRoute: typeof MainMenusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main/food/': {
      id: '/main/food/'
      path: '/main/food'
      fullPath: '/main/food/'
      preLoaderRoute: typeof MainFoodIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main/menus/items': {
      id: '/main/menus/items'
      path: '/main/menus/items'
      fullPath: '/main/menus/items'
      preLoaderRoute: typeof MainMenusItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main/menus/$menuId': {
      id: '/main/menus/$menuId'
      path: '/main/menus/$menuId'
      fullPath: '/main/menus/$menuId'
      preLoaderRoute: typeof MainMenusMenuIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main/food/$itemId': {
      id: '/main/food/$itemId'
      path: '/main/food/$itemId'
      fullPath: '/main/food/$itemId'
      preLoaderRoute: typeof MainFoodItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main/chat/$itemId': {
      id: '/main/chat/$itemId'
      path: '/main/chat/$itemId'
      fullPath: '/main/chat/$itemId'
      preLoaderRoute: typeof MainChatItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  RSlugRoute: RSlugRoute,
  SetupAllergenInfoRoute: SetupAllergenInfoRoute,
  SetupWelcomeRoute: SetupWelcomeRoute,
  SetupIndexRoute: SetupIndexRoute,
  MainChatItemIdRoute: MainChatItemIdRoute,
  MainFoodItemIdRoute: MainFoodItemIdRoute,
  MainMenusMenuIdRoute: MainMenusMenuIdRoute,
  MainMenusItemsRoute: MainMenusItemsRoute,
  MainFoodIndexRoute: MainFoodIndexRoute,
  MainMenusIndexRoute: MainMenusIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
